# Generated by Django 3.2.8 on 2021-12-01 09:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_metadata', '0266_auto_20210624_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerPathway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('name', models.CharField(help_text='Pathway name', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LearnerPathwayStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('pathway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='learner_pathway.learnerpathway')),
            ],
        ),
        migrations.CreateModel(
            name='LearnerPathwayProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learner_pathway_programs', to='course_metadata.program')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learner_pathway.learnerpathwaystep')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LearnerPathwayCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learner_pathway_courses', to='course_metadata.course')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learner_pathway.learnerpathwaystep')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
