# Generated by Django 3.2.8 on 2021-12-07 13:13

from django.db import migrations, models
import django.db.models.deletion
import opaque_keys.edx.django.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0266_auto_20210624_1831'),
        ('learner_pathway', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerPathwayBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('block_id', opaque_keys.edx.django.models.UsageKeyField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learner_pathway_blocks', to='course_metadata.course')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learner_pathway.learnerpathwaystep')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
