# Generated by Django 3.2.8 on 2022-01-19 07:26

import course_discovery.apps.course_metadata.utils
import django.core.validators
from django.db import migrations, models
import djchoices.choices
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('learner_pathway', '0002_learnerpathwayblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerpathway',
            name='banner_image',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to=course_discovery.apps.course_metadata.utils.UploadToFieldNamePath(path='media/learner_pathway/banner_images/', populate_from='uuid')),
        ),
        migrations.AddField(
            model_name='learnerpathway',
            name='overview',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='learnerpathway',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', help_text='The active/inactive status of this Pathway.', max_length=16, validators=[djchoices.choices.ChoicesValidator({'active': 'Active', 'inactive': 'Inactive'})]),
        ),
        migrations.AddField(
            model_name='learnerpathwaystep',
            name='min_requirement',
            field=models.PositiveSmallIntegerField(default=1, help_text='Minimum number of nodes to complete this step of the pathway', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
