# Generated by Django 3.2.10 on 2022-01-19 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0267_remove_course_slug'),
        ('learner_pathway', '0003_auto_20220119_0726'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='learnerpathwaycourse',
            unique_together={('step', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='learnerpathwayprogram',
            unique_together={('step', 'program')},
        ),
    ]
