# Generated by Django 3.2.10 on 2022-01-20 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learner_pathway', '0004_auto_20220119_1338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learnerpathway',
            options={'verbose_name': 'Learner Pathway', 'verbose_name_plural': 'Learner Pathways'},
        ),
        migrations.AlterModelOptions(
            name='learnerpathwaycourse',
            options={'verbose_name': 'Learner Pathway Course', 'verbose_name_plural': 'Learner Pathway Courses'},
        ),
        migrations.AlterModelOptions(
            name='learnerpathwayprogram',
            options={'verbose_name': 'Learner Pathway Program', 'verbose_name_plural': 'Learner Pathway Programs'},
        ),
        migrations.AlterModelOptions(
            name='learnerpathwaystep',
            options={'verbose_name': 'Learner Pathway Step', 'verbose_name_plural': 'Learner Pathway Steps'},
        ),
    ]
