# Generated by Django 3.2.8 on 2022-02-09 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_user_first_name'),
        ('learner_pathway', '0005_auto_20220120_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerpathway',
            name='partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.partner'),
        ),
    ]
