# Generated by Django 3.2.12 on 2022-03-11 06:29

from django.db import migrations, models
from django.db.models import F


def copy_name_to_title(apps, schema_editor):
    LearnerPathway = apps.get_model('learner_pathway', 'LearnerPathway')
    LearnerPathway.objects.all().update(title=F('name'))


class Migration(migrations.Migration):

    dependencies = [
        ('learner_pathway', '0007_learnerpathway_visible_via_association'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerpathway',
            name='title',
            field=models.CharField(default='', help_text='Title of the learner pathway.', max_length=255),
            preserve_default=False,
        ),
        migrations.RunPython(copy_name_to_title, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='learnerpathway',
            name='name',
        ),
    ]
