# Generated by Django 3.2.12 on 2022-04-14 10:49

import course_discovery.apps.course_metadata.utils
from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('learner_pathway', '0008_auto_20220311_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerpathway',
            name='card_image',
            field=stdimage.models.StdImageField(blank=True, help_text='image that will be displayed on learner pathway cards', null=True, upload_to=course_discovery.apps.course_metadata.utils.UploadToFieldNamePath(path='media/learner_pathway/card_images/', populate_from='uuid')),
        ),
        migrations.AlterField(
            model_name='learnerpathway',
            name='banner_image',
            field=stdimage.models.StdImageField(blank=True, help_text='image that will be displayed on learner pathway modal', null=True, upload_to=course_discovery.apps.course_metadata.utils.UploadToFieldNamePath(path='media/learner_pathway/banner_images/', populate_from='uuid')),
        ),
    ]
