# Generated by Django 3.2.20 on 2023-08-09 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner_pathway', '0010_auto_20220822_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnerpathway',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', help_text='The active/inactive status of this Pathway.', max_length=16),
        ),
    ]
