# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-29 20:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0080_seat_bulk_sku'),
        ('journal', '0004_journalbundle_partner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='expires',
        ),
        migrations.AddField(
            model_name='journal',
            name='access_length',
            field=models.IntegerField(default=365, help_text='number of days valid after purchase', null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='card_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='full_description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='organization',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='course_metadata.Organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journal',
            name='short_description',
            field=models.CharField(default=None, max_length=350),
        ),
    ]
