# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-02 21:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_auto_20180329_2009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journal',
            options={'ordering': ('created',)},
        ),
    ]
