# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-03 19:27
from __future__ import unicode_literals

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_auto_20180329_2009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journal',
            options={'ordering': ('created',)},
        ),
        migrations.AlterField(
            model_name='journal',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='UUID'),
        ),
    ]
