# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-03 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0081_auto_20180329_0718'),
        ('journal', '0006_auto_20180402_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalbundle',
            name='applicable_seat_types',
            field=models.ManyToManyField(blank=True, to='course_metadata.SeatType'),
        ),
    ]
