# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-05 12:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0007_journalbundle_applicable_seat_types'),
        ('journal', '0006_auto_20180403_1927'),
    ]

    operations = [
    ]
