# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-05 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0008_merge_20180405_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='uuid',
            field=models.UUIDField(verbose_name='UUID'),
        ),
    ]
