# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-11 20:03
from __future__ import unicode_literals

import djchoices.choices
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0009_auto_20180405_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', help_text='Used to determine whether journal is marketed or not.', max_length=24, validators=[djchoices.choices.ChoicesValidator({'active': 'Active', 'inactive': 'Inactive'})]),
        ),
    ]
