# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-16 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0010_journal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='slug',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
