# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-18 16:46
from __future__ import unicode_literals

import djchoices.choices
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0011_journal_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('retired', 'Retired')], db_index=True, default='active', help_text='Used to determine whether journal is marketed or not.', max_length=24, validators=[djchoices.choices.ChoicesValidator({'active': 'Active', 'inactive': 'Inactive', 'retired': 'Retired'})]),
        ),
        migrations.AlterUniqueTogether(
            name='journal',
            unique_together=set([]),
        ),
    ]
