# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-03 22:19
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    replaces = [('edx_haystack_extensions', '0001_initial'), ('edx_haystack_extensions', '0002_auto_20160826_1750')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElasticsearchBoostConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_score', jsonfield.fields.JSONField(default={'boost': 1.0, 'boost_mode': 'multiply', 'functions': [], 'score_mode': 'multiply'}, help_text='JSON string containing an elasticsearch function score config.', verbose_name='Function Score')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
