# Generated by Django 2.2.12 on 2020-05-06 12:43

from django.db import migrations, models
import django.db.models.deletion
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('ietf_language_tags', '0001_squashed_0005_fix_language_tag_names_again'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageTagTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name_t', models.CharField(max_length=255)),
                ('master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='ietf_language_tags.LanguageTag')),
            ],
            options={
                'unique_together': {('language_code', 'master')},
                'verbose_name': 'LanguageTag model translations',
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
