# Generated by Django 2.2.13 on 2020-09-02 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ietf_language_tags', '0004_auto_20200804_1401'),
        ('ietf_language_tags', '0004_auto_20200825_0827'),
    ]

    operations = [
    ]
