# Generated by Django 1.10.7 on 2017-06-05 09:08


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('core', '0003_auto_20170522_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='site',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sites.Site'),
        ),
    ]
