# Generated by Django 1.11.3 on 2017-08-30 12:46


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_partner_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='site',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='sites.Site'),
        ),
    ]
