# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-12-01 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('core', '0007_auto_20171004_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='partner',
            name='short_code',
            field=models.CharField(help_text='Convenient code/slug used to identify this Partner (e.g. for management commands.)', max_length=8, verbose_name='Short Code'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
        migrations.AlterUniqueTogether(
            name='partner',
            unique_together=set([('short_code', 'site')]),
        ),
    ]
