# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-19 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20171004_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='pubs_api_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Publications API URL'),
        ),
    ]
