# Generated by Django 1.11.15 on 2018-12-17 19:57


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20171004_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='analytics_token',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Analytics Access Token'),
        ),
        migrations.AddField(
            model_name='partner',
            name='analytics_url',
            field=models.URLField(blank=True, default='', max_length=255, verbose_name='Analytics API URL'),
        ),
    ]
