# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-21 14:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_partner_pubs_api_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='pubs_api_url',
        ),
    ]
