# Generated by Django 1.11.15 on 2019-04-04 17:26


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_partner_lms_commerce_api_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='lms_coursemode_api_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Course Mode API URL'),
        ),
    ]
