# Generated by Django 1.11.15 on 2019-04-12 17:31


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_partner_lms_coursemode_api_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='lms_commerce_api_url',
        ),
    ]
