# Generated by Django 1.11.15 on 2019-05-31 13:50


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_partner_lms_commerce_api_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='publisher_url',
            field=models.URLField(blank=True, help_text='The base URL of your publisher service, if used. Example: https://publisher.example.com/', max_length=255, null=True, verbose_name='Publisher URL'),
        ),
    ]
