# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-13 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_historicalpartner'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesforceConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesforce_username', models.CharField(max_length=255, verbose_name='Salesforce Username')),
                ('salesforce_password', models.CharField(max_length=255, verbose_name='Salesforce Password')),
                ('salesforce_organization_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Salesforce Organization Id')),
                ('salesforce_security_token', models.CharField(blank=True, default='', max_length=255, verbose_name='Salesforce Security Token')),
                ('salesforce_is_sandbox', models.BooleanField(default=True, verbose_name='Is a Salesforce Sandbox?')),
                ('partner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Partner')),
            ],
        ),
    ]
