# Generated by Django 1.11.21 on 2019-06-24 15:01


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_historicalsalesforceconfiguration_salesforceconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpartner',
            name='lms_admin_url',
            field=models.URLField(blank=True, help_text='The public URL of your LMS Django admin. Example: https://lms-internal.example.com/admin', max_length=255, null=True, verbose_name='LMS Admin URL'),
        ),
        migrations.AddField(
            model_name='partner',
            name='lms_admin_url',
            field=models.URLField(blank=True, help_text='The public URL of your LMS Django admin. Example: https://lms-internal.example.com/admin', max_length=255, null=True, verbose_name='LMS Admin URL'),
        ),
    ]
