# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-31 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_lms_admin_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsalesforceconfiguration',
            name='case_record_type_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Case Record Type Id'),
        ),
        migrations.AddField(
            model_name='salesforceconfiguration',
            name='case_record_type_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Case Record Type Id'),
        ),
    ]
