# Generated by Django 1.11.22 on 2019-08-13 14:17


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_lms_admin_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsalesforceconfiguration',
            name='case_record_type_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Case Record Type Id'),
        ),
        migrations.AddField(
            model_name='salesforceconfiguration',
            name='case_record_type_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Case Record Type Id'),
        ),
    ]
