# Generated by Django 1.11.26 on 2019-11-26 16:48


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_case_record_type_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpartner',
            name='oidc_key',
        ),
        migrations.RemoveField(
            model_name='historicalpartner',
            name='oidc_secret',
        ),
        migrations.RemoveField(
            model_name='historicalpartner',
            name='oidc_url_root',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='oidc_key',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='oidc_secret',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='oidc_url_root',
        ),
    ]
