# Generated by Django 2.2.16 on 2024-04-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200414_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpartner',
            name='is_disabled',
            field=models.BooleanField(default=False, verbose_name='Disable Partner'),
        ),
        migrations.AddField(
            model_name='partner',
            name='is_disabled',
            field=models.BooleanField(default=False, verbose_name='Disable Partner'),
        ),
    ]
