# Generated by Django 1.9.10 on 2016-11-03 22:01


import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('catalogs', '0001_initial'), ('catalogs', '0002_auto_20160327_2101')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created',
                 django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified',
                 django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(help_text='Catalog name', max_length=255)),
                ('query', models.TextField(help_text='Query to retrieve catalog contents')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'permissions': (('view_catalog', 'Can view catalog'),),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
