# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-03 22:01
from __future__ import unicode_literals

import django_extensions.db.fields
from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('catalogs', '0001_initial'), ('catalogs', '0002_auto_20160327_2101')]

    initial = True

    dependencies = [
    ]

    def create_view_permission(apps, schema_editor):
        content_type = ContentType.objects.get(app_label="catalogs", model="catalog")
        # Django 2.1 creates these views by default, so this ensures we don't violate uniqueness constraints.
        if not Permission.objects.filter(codename='view_catalog').exists():
            Permission.objects.get_or_create(
                codename='view_catalog',
                name='Can view catalog',
                content_type=content_type,
            )

    def destroy_view_permission(apps, schema_editor):
        try:
            permission = Permission.objects.get(codename='view_catalog')
            permission.delete()
        except Permission.DoesNotExist:
            pass

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created',
                 django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified',
                 django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(help_text='Catalog name', max_length=255)),
                ('query', models.TextField(help_text='Query to retrieve catalog contents')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.RunPython(code=create_view_permission, reverse_code=destroy_view_permission)
    ]
