# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-19 12:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0002_catalog_include_archived'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalog',
            options={'default_permissions': ('add', 'change', 'delete'), 'get_latest_by': 'modified', 'ordering': ('-modified', '-created'), 'permissions': (('view_catalog', 'Can view catalog'),)},
        ),
    ]
