# Generated by Django 2.2 on 2020-03-18 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0002_catalog_include_archived'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalog',
            options={'default_permissions': (), 'get_latest_by': 'modified', 'ordering': ('-modified', '-created'), 'permissions': (('view_catalog', 'Can view catalog'),)},
        ),
    ]
