# Generated by Django 2.2 on 2020-03-20 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0003_auto_20200318_0924'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalog',
            options={'default_permissions': ('add', 'change', 'delete'), 'get_latest_by': 'modified', 'ordering': ('-modified', '-created'), 'permissions': (('view_catalog', 'Can view catalog'),)},
        ),
    ]
