# Generated by Django 2.2.12 on 2020-04-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0003_auto_20200331_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='program_query',
            field=models.TextField(blank=True, default='', help_text='Query to retrieve Program catalog contents'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='query',
            field=models.TextField(help_text='Query to retrieve Course Run catalog contents'),
        ),
    ]
