# Generated by Django 2.2.14 on 2020-08-04 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0004_add_programs_query'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalog',
            options={'default_permissions': ('add', 'change', 'delete'), 'get_latest_by': 'modified', 'permissions': (('view_catalog', 'Can view catalog'),)},
        ),
    ]
