# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-05 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0016_auto_20161105_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationsroles',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='course_metadata.Organization'),
        ),
    ]
