# Generated by Django 1.9.11 on 2016-12-14 13:56


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0020_auto_20161214_1304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationextension',
            options={'get_latest_by': 'modified', 'ordering': ('-modified', '-created'), 'permissions': (('edit_course_run', 'Can edit course run'),)},
        ),
    ]
