# Generated by Django 1.9.11 on 2016-12-22 21:35


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0021_auto_20161214_1356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationextension',
            options={'get_latest_by': 'modified', 'ordering': ('-modified', '-created'), 'permissions': (('edit_course_run', 'Can edit course run'), ('publisher_view_course', 'Can view course'), ('publisher_view_course_run', 'Can view the course run'))},
        ),
    ]
