# Generated by Django 1.9.11 on 2016-12-28 13:50


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0022_auto_20161222_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='team_admin',
        ),
        migrations.RemoveField(
            model_name='historicalcourse',
            name='team_admin',
        ),
    ]
