# Generated by Django 1.9.11 on 2017-01-05 16:26


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0023_auto_20161228_1350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationextension',
            options={'get_latest_by': 'modified', 'ordering': ('-modified', '-created'), 'permissions': (('publisher_edit_course', 'Can edit course'), ('publisher_edit_course_run', 'Can edit course run'), ('publisher_view_course', 'Can view course'), ('publisher_view_course_run', 'Can view the course run'))},
        ),
    ]
