# Generated by Django 1.9.11 on 2017-01-04 18:30


import stdimage.models
import stdimage.validators
from django.db import migrations, models

import course_discovery.apps.course_metadata.utils


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0024_auto_20170105_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to=course_discovery.apps.course_metadata.utils.UploadToFieldNamePath('number', path='media/publisher/courses/images'), validators=[stdimage.validators.MaxSizeValidator(2120, 1192), stdimage.validators.MinSizeValidator(2120, 1192)]),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='image',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[stdimage.validators.MaxSizeValidator(2120, 1192), stdimage.validators.MinSizeValidator(2120, 1192)]),
        ),
    ]
