# Generated by Django 1.9.12 on 2017-02-15 14:13


import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_partner_studio_url'),
        ('publisher', '0034_auto_20170213_0918'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublisherUser',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('core.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
