# Generated by Django 1.9.12 on 2017-02-21 11:50


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0036_auto_20170216_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserunstate',
            name='preview_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcourserunstate',
            name='preview_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
