# Generated by Django 1.9.12 on 2017-02-23 12:41


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0039_rename_partner_coordinator_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalstate',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='historicalstate',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='state',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='courserun',
            name='state',
        ),
        migrations.RemoveField(
            model_name='historicalcourserun',
            name='state',
        ),
        migrations.DeleteModel(
            name='HistoricalState',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
