# Generated by Django 1.9.12 on 2017-03-23 07:49


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0043_auto_20170321_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursestate',
            name='marketing_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcoursestate',
            name='marketing_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
