# Generated by Django 1.9.12 on 2017-03-30 07:29


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0044_auto_20170323_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='faq',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='FAQ'),
        ),
        migrations.AddField(
            model_name='course',
            name='video_link',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='Video Link'),
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='faq',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='FAQ'),
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='video_link',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='Video Link'),
        ),
        migrations.AlterField(
            model_name='course',
            name='learner_testimonial',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Learner Testimonials'),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='learner_testimonial',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Learner Testimonials'),
        ),
    ]
