# Generated by Django 1.9.13 on 2017-04-13 09:35


import stdimage.models
from django.db import migrations, models

import course_discovery.apps.course_metadata.utils
import course_discovery.apps.publisher.validators


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0045_auto_20170330_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to=course_discovery.apps.course_metadata.utils.UploadToFieldNamePath('number', path='media/publisher/courses/images'), validators=[course_discovery.apps.publisher.validators.ImageSizeValidator(height=1192, width=2120)]),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='image',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[course_discovery.apps.publisher.validators.ImageSizeValidator(height=1192, width=2120)]),
        ),
    ]
