# Generated by Django 1.9.11 on 2017-04-13 10:10


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0046_auto_20170413_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='short_description',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Brief Description'),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='short_description',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Brief Description'),
        ),
    ]
