# Generated by Django 1.9.13 on 2017-05-11 10:59


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0047_auto_20170413_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorganizationuserrole',
            name='role',
            field=models.CharField(choices=[('partner_manager', 'Partner Manager'), ('project_coordinator', 'Project Coordinator'), ('marketing_reviewer', 'Marketing Reviewer'), ('publisher', 'Publisher')], max_length=63, verbose_name='Organization Role'),
        ),
        migrations.AlterField(
            model_name='organizationuserrole',
            name='role',
            field=models.CharField(choices=[('partner_manager', 'Partner Manager'), ('project_coordinator', 'Project Coordinator'), ('marketing_reviewer', 'Marketing Reviewer'), ('publisher', 'Publisher')], max_length=63, verbose_name='Organization Role'),
        ),
    ]
