# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-04-30 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0047_auto_20170413_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='card_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='card_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
