# Generated by Django 1.10.7 on 2017-05-24 19:09


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0049_auto_20170518_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserun',
            name='card_image_url',
            field=models.URLField(blank=True, null=True, verbose_name='canonical course run image'),
        ),
        migrations.AddField(
            model_name='historicalcourserun',
            name='card_image_url',
            field=models.URLField(blank=True, null=True, verbose_name='canonical course run image'),
        ),
    ]
