# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-23 10:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0054_update_program_type_slug_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publisher', '0049_auto_20170518_1017'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseuserrole',
            unique_together=set([('course', 'user'), ('course', 'role')]),
        ),
        migrations.AlterUniqueTogether(
            name='organizationuserrole',
            unique_together=set([('organization', 'role'), ('organization', 'user')]),
        ),
    ]
