# Generated by Django 1.10.7 on 2017-06-20 15:00


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0054_auto_20170605_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserun',
            name='short_description_override',
            field=models.CharField(blank=True, default=None, help_text="Short description specific for this run of a course. Leave this value blank to default to the parent course's short_description attribute.", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalcourserun',
            name='short_description_override',
            field=models.CharField(blank=True, default=None, help_text="Short description specific for this run of a course. Leave this value blank to default to the parent course's short_description attribute.", max_length=255, null=True),
        ),
    ]
