# Generated by Django 1.11.3 on 2017-09-20 18:21


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0056_auto_20170621_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='verification_deadline',
        ),
        migrations.RemoveField(
            model_name='historicalcourse',
            name='verification_deadline',
        ),
    ]
