# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 19:02
from __future__ import unicode_literals

import stdimage.models
from django.db import migrations, models

import course_discovery.apps.course_metadata.utils
import course_discovery.apps.publisher.validators


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0056_auto_20170621_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='video_preview_image',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to=course_discovery.apps.course_metadata.utils.UploadToFieldNamePath('number', path='media/publisher/courses/video_preview_image'), validators=[course_discovery.apps.publisher.validators.ImageSizeValidator(height=900, width=1512)]),
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='video_preview_image',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[course_discovery.apps.publisher.validators.ImageSizeValidator(height=900, width=1512)]),
        ),
    ]
