# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-25 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0057_auto_20170920_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courserun',
            name='enrollment_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Enrollment End Date'),
        ),
        migrations.AlterField(
            model_name='courserun',
            name='enrollment_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Enrollment Start Date'),
        ),
        migrations.AlterField(
            model_name='historicalcourserun',
            name='enrollment_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Enrollment End Date'),
        ),
        migrations.AlterField(
            model_name='historicalcourserun',
            name='enrollment_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Enrollment Start Date'),
        ),
    ]
