# Generated by Django 1.11.3 on 2017-09-27 17:58


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0057_auto_20170920_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorganizationextension',
            name='auto_create_in_studio',
            field=models.BooleanField(default=True, help_text='When this flag is enabled, creation of a new course run in Publisher will also create a corresponding course run in Studio.', verbose_name='Automatically create a run in Studio'),
        ),
        migrations.AddField(
            model_name='organizationextension',
            name='auto_create_in_studio',
            field=models.BooleanField(default=True, help_text='When this flag is enabled, creation of a new course run in Publisher will also create a corresponding course run in Studio.', verbose_name='Automatically create a run in Studio'),
        ),
    ]
