# Generated by Django 1.11.3 on 2017-09-28 04:25


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0058_auto_20170927_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalcourse',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalcourserun',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalcourserunstate',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalcoursestate',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalcourseuserrole',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalorganizationextension',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalorganizationuserrole',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalseat',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
