# Generated by Django 1.11.3 on 2017-10-04 05:21


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0059_auto_20170928_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalseat',
            name='type',
            field=models.CharField(choices=[('honor', 'Honor'), ('audit', 'Audit'), ('verified', 'Verified'), ('professional', 'Professional (with ID verification)'), ('no-id-professional', 'Professional (no ID verification)'), ('credit', 'Credit')], max_length=63, verbose_name='Seat type'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='type',
            field=models.CharField(choices=[('honor', 'Honor'), ('audit', 'Audit'), ('verified', 'Verified'), ('professional', 'Professional (with ID verification)'), ('no-id-professional', 'Professional (no ID verification)'), ('credit', 'Credit')], max_length=63, verbose_name='Seat type'),
        ),
    ]
