# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-04 13:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0059_auto_20170928_0425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcourse',
            name='history_change_reason',
        ),
        migrations.RemoveField(
            model_name='historicalcourserun',
            name='history_change_reason',
        ),
        migrations.RemoveField(
            model_name='historicalcourserunstate',
            name='history_change_reason',
        ),
        migrations.RemoveField(
            model_name='historicalcoursestate',
            name='history_change_reason',
        ),
        migrations.RemoveField(
            model_name='historicalcourseuserrole',
            name='history_change_reason',
        ),
        migrations.RemoveField(
            model_name='historicalorganizationextension',
            name='history_change_reason',
        ),
        migrations.RemoveField(
            model_name='historicalorganizationuserrole',
            name='history_change_reason',
        ),
        migrations.RemoveField(
            model_name='historicalseat',
            name='history_change_reason',
        ),
    ]
