# Generated by Django 1.11.3 on 2017-12-19 18:41


import stdimage.models
from django.db import migrations, models

import course_discovery.apps.course_metadata.utils
import course_discovery.apps.publisher.validators


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0062_auto_20171212_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to=course_discovery.apps.course_metadata.utils.UploadToFieldNamePath('number', path='media/publisher/courses/images'), validators=[course_discovery.apps.publisher.validators.ImageMultiSizeValidator([(2120, 1192), (378, 225)], preferred_size=(1134, 675))]),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='image',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[course_discovery.apps.publisher.validators.ImageMultiSizeValidator([(2120, 1192), (378, 225)], preferred_size=(1134, 675))]),
        ),
    ]
