# Generated by Django 1.11.3 on 2018-05-07 09:51


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0064_auto_20180125_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courserun',
            name='enrollment_end',
        ),
        migrations.RemoveField(
            model_name='courserun',
            name='enrollment_start',
        ),
        migrations.RemoveField(
            model_name='historicalcourserun',
            name='enrollment_end',
        ),
        migrations.RemoveField(
            model_name='historicalcourserun',
            name='enrollment_start',
        ),
    ]
