# Generated by Django 1.11.15 on 2018-10-30 14:26


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0066_add_default_pacing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='additional_information',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Additional Information'),
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='additional_information',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Additional Information'),
        ),
    ]
