# Generated by Django 1.11.15 on 2018-11-05 16:30


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0067_auto_20181030_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='has_ofac_restrictions',
            field=models.BooleanField(default=False, verbose_name='Course Has OFAC Restrictions'),
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='has_ofac_restrictions',
            field=models.BooleanField(default=False, verbose_name='Course Has OFAC Restrictions'),
        ),
    ]
