# Generated by Django 1.11.15 on 2018-12-05 15:28


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0070_drupalloaderconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drupalloaderconfig',
            name='course_run_ids',
            field=models.TextField(default=None, verbose_name='Course Run IDs'),
        ),
        migrations.AlterField(
            model_name='drupalloaderconfig',
            name='partner_code',
            field=models.TextField(default=None, verbose_name='Partner Code'),
        ),
    ]
