# Generated by Django 1.11.15 on 2018-12-19 21:00


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0071_auto_20181205_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courserun',
            name='short_description_override',
            field=models.TextField(blank=True, default=None, help_text="Short description specific for this run of a course. Leave this value blank to default to the parent course's short_description attribute.", null=True),
        ),
        migrations.AlterField(
            model_name='historicalcourserun',
            name='short_description_override',
            field=models.TextField(blank=True, default=None, help_text="Short description specific for this run of a course. Leave this value blank to default to the parent course's short_description attribute.", null=True),
        ),
    ]
