# Generated by Django 1.11.15 on 2019-01-02 17:45


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0072_auto_20181219_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='drupalloaderconfig',
            name='load_unpublished_course_runs',
            field=models.BooleanField(default=False),
        ),
    ]
