# Generated by Django 1.11.15 on 2019-02-13 20:15


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0074_remove_preview_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalcourse',
            name='level_type',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='course_metadata.LevelType', verbose_name='Level Type'),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='primary_subject',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='course_metadata.Subject'),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='secondary_subject',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='course_metadata.Subject'),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='tertiary_subject',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='course_metadata.Subject'),
        ),
        migrations.AlterField(
            model_name='historicalcourserun',
            name='language',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ietf_language_tags.LanguageTag', verbose_name='Content Language'),
        ),
        migrations.AlterField(
            model_name='historicalseat',
            name='currency',
            field=models.ForeignKey(blank=True, db_constraint=False, default='USD', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Currency'),
        ),
    ]
