# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-09 20:52
from __future__ import unicode_literals

from urllib.parse import urljoin

from django.db import migrations, models


def forwards_func(apps, _schema_editor):
    CourseRun = apps.get_model('publisher', 'CourseRun')
    DiscoveryCourseRun = apps.get_model('course_metadata', 'CourseRun')

    for run in CourseRun.objects.exclude(lms_course_id__isnull=True).exclude(lms_course_id=''):
        discovery_run = DiscoveryCourseRun.objects.filter(key=run.lms_course_id).first()
        if not discovery_run or not discovery_run.slug:
            continue

        path = 'course/{slug}'.format(slug=discovery_run.slug)
        run.preview_url = urljoin(discovery_run.course.partner.marketing_site_url_root, path)
        run.save()


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0074_remove_preview_url'),
        ('course_metadata', '0001_squashed_0033_courserun_mobile_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserun',
            name='preview_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcourserun',
            name='preview_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.RunPython(forwards_func),
    ]
