# Generated by Django 1.11.15 on 2019-04-09 16:29


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0075_auto_20190213_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalseat',
            name='masters_track',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seat',
            name='masters_track',
            field=models.BooleanField(default=False),
        ),
    ]
