# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-27 21:10
from __future__ import unicode_literals

from django.db import migrations
from course_discovery.apps.publisher.models import Course

def migrate_data_forward(apps, schema_editor):
    for instance in Course.objects.all():
        course_metadata_course = instance.discovery_counterpart
        if course_metadata_course:
            instance.url_slug = course_metadata_course.url_slug
        instance.save()


def migrate_data_backward(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0195_save_all_url_slugs'),
        ('publisher', '0079_course_url_slug')
    ]

    operations = [
        migrations.RunPython(
            migrate_data_forward,
            migrate_data_backward,
        ),
    ]
