# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-29 20:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0080_remove_publisher_waffle_switches'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='url_slug',
        ),
    ]
