# Generated by Django 1.11.24 on 2019-11-04 20:19


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0085_remove_course_has_ofac_restrictions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorganizationextension',
            name='auto_create_in_studio',
            field=models.NullBooleanField(default=True, help_text='When this flag is enabled, creation of a new course run in Publisher will also create a corresponding course run in Studio.', verbose_name='Automatically create a run in Studio'),
        ),
        migrations.AlterField(
            model_name='organizationextension',
            name='auto_create_in_studio',
            field=models.NullBooleanField(default=True, help_text='When this flag is enabled, creation of a new course run in Publisher will also create a corresponding course run in Studio.', verbose_name='Automatically create a run in Studio'),
        ),
    ]
