# Generated by Django 1.11.24 on 2019-11-05 18:30


from django.db import migrations


def populate_auto_create_in_studio(apps, schema_editor):
    OrganizationExtension = apps.get_model('publisher', 'OrganizationExtension')
    org_extensions = OrganizationExtension.objects.all()
    for ext in org_extensions:
        ext.auto_create_in_studio = ext.organization.auto_generate_course_run_keys
        ext.save()


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0086_make_auto_create_in_studio_null_boolean'),
    ]

    operations = [
        migrations.RunPython(migrations.RunPython.noop, populate_auto_create_in_studio),
        migrations.RemoveField(
            model_name='historicalorganizationextension',
            name='auto_create_in_studio',
        ),
        migrations.RemoveField(
            model_name='organizationextension',
            name='auto_create_in_studio',
        ),
    ]
