# Generated by Django 1.11.27 on 2020-01-21 16:53


from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('publisher_comments', '0001_initial'), ('publisher_comments', '0002_comments_comment_type'), ('publisher_comments', '0003_drop_tables')]

    initial = True

    dependencies = [
    ]

    operations = [
    ]
