# Generated by Django 1.9.11 on 2017-02-24 09:38


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher_comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment_type',
            field=models.CharField(blank=True, choices=[('default', 'Default'), ('decline_preview', 'Decline Preview')], default='default', max_length=255, null=True),
        ),
    ]
