# Generated by Django 3.2.12 on 2022-03-31 08:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_metadata', '0273_add_facts_and_cert_info_data_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRecommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('skills_intersection_ratio', models.FloatField(help_text='Ratio of number of common skills and total skill count.')),
                ('skills_intersection_length', models.IntegerField(help_text='Count of common skills between the original course and recommended course.')),
                ('subjects_intersection_ratio', models.FloatField(help_text='Ratio of number of common subjects and total subject count.')),
                ('subjects_intersection_length', models.IntegerField(help_text='Count of common subjects between the original course and recommended course.')),
                ('course', models.ForeignKey(help_text='The original course, whose recommendation is stored here.', on_delete=django.db.models.deletion.CASCADE, related_name='course_recommendations', to='course_metadata.course')),
                ('recommended_course', models.ForeignKey(help_text='This is the course recommended after learner completes the original course.', on_delete=django.db.models.deletion.CASCADE, to='course_metadata.course')),
            ],
            options={
                'verbose_name': 'Course Recommendation',
                'verbose_name_plural': 'Course Recommendations',
                'unique_together': {('course', 'recommended_course')},
            },
        ),
    ]
