# Generated by Django 3.2.8 on 2022-04-06 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy_support', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateCourseRecommendationsConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_courses', models.BooleanField(default=False, verbose_name='Adds recommendations for all published courses')),
                ('uuids', models.TextField(blank=True, default='', verbose_name='Course uuids')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
