# Generated by Django 1.9.10 on 2016-11-03 21:29


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0034_auto_20161103_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='banner_image_url',
            field=models.URLField(blank=True, help_text='DEPRECATED: Use the banner image field.', null=True),
        ),
    ]
