# Generated by Django 1.9.11 on 2017-01-17 21:14


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0040_auto_20161220_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='certificate_logo_image_url',
            field=models.URLField(blank=True, help_text='Logo to be displayed on certificates. If this logo is the same as logo_image_url, copy and paste the same value to both fields.', null=True),
        ),
    ]
