# Generated by Django 1.9.11 on 2017-01-19 09:18


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0041_organization_certificate_logo_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporateendorsement',
            name='statement',
            field=models.TextField(blank=True, null=True),
        ),
    ]
