# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-23 19:51
from __future__ import unicode_literals

import stdimage.models
import stdimage.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0044_auto_20170131_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='profile_image',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to=stdimage.utils.UploadToAutoSlug('uuid', path='media/people/profile_images')),
        ),
    ]
