# Generated by Django 1.9.11 on 2017-02-06 20:45


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0045_person_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserun',
            name='reporting_type',
            field=models.CharField(choices=[('mooc', 'mooc'), ('spoc', 'spoc'), ('test', 'test'), ('demo', 'demo'), ('other', 'other')], default='mooc', max_length=255),
        ),
    ]
