# Generated by Django 1.9.11 on 2017-02-21 20:11


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0047_personwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataLoaderConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_workers', models.PositiveSmallIntegerField(default=7)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
