# Generated by Django 1.9.12 on 2017-03-20 11:30


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0048_dataloaderconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserun',
            name='eligible_for_financial_aid',
            field=models.BooleanField(default=True),
        ),
    ]
