# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-24 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0054_update_program_type_slug_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='hidden',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
