# Generated by Django 1.10.7 on 2017-06-01 16:13


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0054_update_program_type_slug_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='hidden',
            field=models.BooleanField(db_index=True, default=False, help_text='Hide program on marketing site landing and search pages. This program MAY have a detail page.'),
        ),
    ]
