# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-08 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0056_auto_20170620_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='programtype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
