# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0056_auto_20170620_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='family_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
