# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 19:02
from __future__ import unicode_literals

import stdimage.models
import stdimage.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ietf_language_tags', '0001_squashed_0005_fix_language_tag_names_again'),
        ('course_metadata', '0056_auto_20170620_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=stdimage.models.StdImageField(blank=True, help_text='Please provide a course preview image', null=True, upload_to=stdimage.utils.UploadToAutoSlug('uuid', path='media/course/image')),
        ),
        migrations.AddField(
            model_name='course',
            name='outcome',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courserun',
            name='learner_testimonials',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courserun',
            name='video_translation_languages',
            field=models.ManyToManyField(blank=True, related_name='video_translation_course_runs', to='ietf_language_tags.LanguageTag'),
        ),
        migrations.AddField(
            model_name='video',
            name='preview_image',
            field=stdimage.models.StdImageField(blank=True, help_text='Please provide an image file previewing the video', null=True, upload_to=stdimage.utils.UploadToAutoSlug('id', path='media/video/preview_image')),
        ),
    ]
