# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0057_auto_20170802_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='end_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='start_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
