# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0058_auto_20170802_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='continuing_education_units',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
