# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0059_program_continuing_education_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='continuing_education_units',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
