# Generated by Django 1.11.3 on 2017-10-18 15:28


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0063_auto_20171005_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjecttranslation',
            name='description_t',
        ),
        migrations.RemoveField(
            model_name='subjecttranslation',
            name='name_t',
        ),
        migrations.RemoveField(
            model_name='subjecttranslation',
            name='subtitle_t',
        ),
    ]
