# Generated by Django 1.11.3 on 2017-10-20 13:40


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0064_auto_20171018_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='total_hours_of_effort',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Total estimated time needed to complete all courses belonging to this program. This field is intended for display on program certificates.', null=True),
        ),
    ]
