# Generated by Django 1.11.3 on 2017-11-16 17:08


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0068_auto_20171108_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseentitlement',
            name='expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
