# Generated by Django 1.11.3 on 2017-11-27 10:57


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0069_courseentitlement_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='key',
            field=models.CharField(help_text="Please do not use any spaces or special characters other than period, underscore or hyphen. This key will be used in the course's course key.", max_length=255),
        ),
    ]
