# Generated by Django 1.11.3 on 2017-11-29 15:20


import sortedm2m.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0072_courseentitlement_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='instructors',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text='Used to organize the instructors on the program about page.', to='course_metadata.Person'),
        ),
    ]
