# Generated by Django 1.11.3 on 2017-12-12 20:16


import django.db.models.deletion
import stdimage.models
from django.db import migrations, models

import course_discovery.apps.course_metadata.utils


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0073_program_instructors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=stdimage.models.StdImageField(blank=True, help_text='Please provide a course preview image', null=True, upload_to=course_discovery.apps.course_metadata.utils.UploadToFieldNamePath('uuid', path='media/course/image')),
        ),
        migrations.AlterField(
            model_name='courseentitlement',
            name='partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Partner'),
        ),
        migrations.AlterField(
            model_name='person',
            name='profile_image',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to=course_discovery.apps.course_metadata.utils.UploadToFieldNamePath('uuid', path='media/people/profile_images')),
        ),
    ]
