# Generated by Django 1.11.3 on 2017-12-11 19:22


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0074_auto_20171212_2016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='instructors',
            new_name='instructor_ordering',
        ),
    ]
