# Generated by Django 1.11.3 on 2017-12-19 18:41


import sortedm2m.fields
import stdimage.models
from django.db import migrations

import course_discovery.apps.course_metadata.utils


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0075_auto_20171211_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=stdimage.models.StdImageField(blank=True, help_text='Add the course image', null=True, upload_to=course_discovery.apps.course_metadata.utils.UploadToFieldNamePath('uuid', path='media/course/image')),
        ),
        migrations.AlterField(
            model_name='program',
            name='instructor_ordering',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text='This field can be used by API clients to determine the order in which instructors will be displayed on program pages. Instructors in this list should appear before all others associated with this programs courses runs.', to='course_metadata.Person'),
        ),
    ]
