# Generated by Django 1.11.3 on 2018-01-26 12:04


import sortedm2m.fields
from django.db import migrations
from sortedm2m.operations import AlterSortedManyToManyField


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0076_auto_20171219_1841'),
    ]

    operations = [
        AlterSortedManyToManyField(
            model_name='course',
            name='subjects',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='course_metadata.Subject'),
        ),
    ]
