# Generated by Django 1.11.3 on 2018-02-09 10:44


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0077_auto_20180131_1956'),
        ('course_metadata', '0077_auto_20180126_1204'),
    ]

    operations = [
    ]
