# Generated by Django 1.11.3 on 2018-03-19 17:18


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0078_merge_20180209_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='one_click_purchase_enabled',
            field=models.BooleanField(default=True, help_text='Allow courses in this program to be purchased in a single transaction'),
        ),
    ]
