# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-07 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0078_merge_20180209_1044'),
        ('course_metadata', '0078_digitalbookbundle'),
    ]

    operations = [
    ]
