# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-07 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0079_merge_20180307_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digitalbookbundle',
            name='course',
        ),
        migrations.AddField(
            model_name='digitalbookbundle',
            name='courses',
            field=models.ManyToManyField(blank=True, to='course_metadata.Course'),
        ),
    ]
