# Generated by Django 1.11.3 on 2018-03-09 19:38


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0079_enable_program_default_true'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='bulk_sku',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
