# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-19 21:31
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0080_auto_20180307_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('key', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
                'ordering': ('-modified', '-created'),
            },
        ),
        migrations.RemoveField(
            model_name='digitalbookbundle',
            name='book_key',
        ),
        migrations.AddField(
            model_name='digitalbookbundle',
            name='pubs',
            field=models.ManyToManyField(blank=True, to='course_metadata.Pub'),
        ),
    ]
