# Generated by Django 1.11.3 on 2018-03-30 12:18


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0081_auto_20180329_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='salutation',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
