# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-19 22:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_partner_pubs_api_url'),
        ('course_metadata', '0081_auto_20180319_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='pub',
            name='partner',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='core.Partner'),
            preserve_default=False,
        ),
    ]
