# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-20 14:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0082_pub_partner'),
        ('course_metadata', '0079_enable_program_default_true'),
    ]

    operations = [
    ]
