# Generated by Django 1.11.11 on 2018-05-22 13:39


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0083_auto_20180511_1406'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='courseentitlement',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='courserunsocialnetwork',
            options={'ordering': ['created'], 'verbose_name_plural': 'CourseRun SocialNetwork'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['created'], 'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQs'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['created'], 'verbose_name_plural': 'People'},
        ),
        migrations.AlterModelOptions(
            name='personsocialnetwork',
            options={'ordering': ['created'], 'verbose_name_plural': 'Person SocialNetwork'},
        ),
        migrations.AlterModelOptions(
            name='seat',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['created']},
        ),
    ]
