# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-04-09 09:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ietf_language_tags', '0001_squashed_0005_fix_language_tag_names_again'),
        ('course_metadata', '0084_auto_20180522_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='description',
            field=models.TextField(blank=True, default=None, help_text="Description specific for this program. It would be displayed on the Program's details page.", null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='duration',
            field=models.IntegerField(default=0, help_text='Time spend of program'),
        ),
        migrations.AddField(
            model_name='program',
            name='enrollment_end',
            field=models.DateTimeField(blank=True, help_text='End date of program', null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='enrollment_start',
            field=models.DateTimeField(blank=True, help_text='Start date of program', null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ietf_language_tags.LanguageTag'),
        ),
    ]
