# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-06-14 03:51
from __future__ import unicode_literals

import course_discovery.apps.course_metadata.utils
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0085_auto_20210409_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='enrollment_end',
        ),
        migrations.RemoveField(
            model_name='program',
            name='enrollment_start',
        ),
        migrations.AddField(
            model_name='program',
            name='creator_id',
            field=models.IntegerField(help_text='Program Creator(user) id', null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='card_image_url',
            field=stdimage.models.StdImageField(blank=True, help_text='Image used for discovery cards', max_length=200, null=True, upload_to=course_discovery.apps.course_metadata.utils.UploadToFieldNamePath('uuid', path='media/programs/card_images')),
        ),
        migrations.AlterField(
            model_name='program',
            name='order_courses_by_start_date',
            field=models.BooleanField(default=False, help_text='If this box is not checked, courses will be ordered as in the courses select box above.', verbose_name='Order Courses By Start Date'),
        ),
    ]
