# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-16 17:11
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0086_auto_20180712_1854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='degreemarketing',
            options={'verbose_name_plural': 'degrees marketing'},
        ),
        migrations.AddField(
            model_name='degreemarketing',
            name='program',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='course_metadata.Program'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='degreemarketing',
            name='application_deadline',
            field=models.CharField(blank=True, help_text='String-based deadline field (e.g. FALL 2020)', max_length=255),
        ),
    ]
