# Generated by Django 1.11.11 on 2018-07-18 20:16


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0086_auto_20180712_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditpathway',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditpathway',
            name='destination_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
