# Generated by Django 1.11.11 on 2018-07-23 13:56


import uuid

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0087_auto_20180718_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='DegreeCourseCurriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_metadata.Course')),
            ],
            options={
                'abstract': False,
                'get_latest_by': 'modified',
                'ordering': ('-modified', '-created'),
            },
        ),
        migrations.CreateModel(
            name='DegreeProgramCurriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
            ],
            options={
                'abstract': False,
                'get_latest_by': 'modified',
                'ordering': ('-modified', '-created'),
            },
        ),
        migrations.AlterModelOptions(
            name='degreemarketing',
            options={'verbose_name_plural': 'degrees marketing'},
        ),
        migrations.AddField(
            model_name='degree',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='degree',
            name='program',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='degree', to='course_metadata.Program'),
        ),
        migrations.AddField(
            model_name='degreeprogramcurriculum',
            name='degree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_metadata.Degree'),
        ),
        migrations.AddField(
            model_name='degreeprogramcurriculum',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_metadata.Program'),
        ),
        migrations.AddField(
            model_name='degreecoursecurriculum',
            name='degree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_metadata.Degree'),
        ),
        migrations.AddField(
            model_name='degree',
            name='course_curriculum',
            field=models.ManyToManyField(related_name='degree_course_curricula', through='course_metadata.DegreeCourseCurriculum', to='course_metadata.Course'),
        ),
        migrations.AddField(
            model_name='degree',
            name='program_curriculum',
            field=models.ManyToManyField(related_name='degree_program_curricula', through='course_metadata.DegreeProgramCurriculum', to='course_metadata.Program'),
        ),
    ]
