# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-08-05 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0087_auto_20210707_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='released_date',
            field=models.DateTimeField(blank=True, help_text='Program Released(published) date', null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='card_image_url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
