# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2022-01-11 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0088_auto_20210805_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='card_image_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
