# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-25 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0088_degreeprogramrelationship'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='degreemarketing',
            options={'verbose_name_plural': 'degrees marketing'},
        ),
        migrations.AddField(
            model_name='degreemarketing',
            name='overall_ranking',
            field=models.CharField(blank=True, help_text='Overall program ranking (e.g. "#1 in the U.S.")', max_length=255),
        ),
        migrations.AddField(
            model_name='degreemarketing',
            name='campus_image_desktop',
            field=models.ImageField(blank=True, help_text='Provide a campus image to display on desktop displays', null=True, upload_to='media/degree_marketing/campus_images/'),
        ),
        migrations.AddField(
            model_name='degreemarketing',
            name='campus_image_mobile',
            field=models.ImageField(blank=True, help_text='Provide a campus image to display on mobile displays', null=True, upload_to='media/degree_marketing/campus_images/'),
        ),
        migrations.AddField(
            model_name='degreemarketing',
            name='campus_image_tablet',
            field=models.ImageField(blank=True, help_text='Provide a campus image to display on tablet displays', null=True, upload_to='media/degree_marketing/campus_images/'),
        ),
    ]
