# Generated by Django 1.11.11 on 2018-07-25 16:02


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20171004_1133'),
        ('course_metadata', '0088_degreeprogramrelationship'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditpathway',
            options={},
        ),
        migrations.AddField(
            model_name='creditpathway',
            name='partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Partner'),
        ),
        migrations.AlterField(
            model_name='creditpathway',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='creditpathway',
            unique_together={('partner', 'name')},
        ),
    ]
