# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2022-01-18 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0089_auto_20220111_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courserun',
            name='key',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
