# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2022-07-21 06:50
from __future__ import unicode_literals

from django.db import migrations, models
import djchoices.choices


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0089_auto_20220111_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='visibility',
            field=models.IntegerField(choices=[(0, 'Full public'), (1, 'Accessible by URL'), (2, 'Private')], default=0, help_text='Visibility of program', validators=[djchoices.choices.ChoicesValidator({0: 'Full public', 1: 'Accessible by URL', 2: 'Private'})]),
        ),
    ]
