# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2022-09-21 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0089_auto_20220111_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='card_image_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='courserun',
            name='card_image_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
