# Generated by Django 1.11.11 on 2018-07-27 18:44


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0090_degree_curriculum_reset'),
    ]

    operations = [
        migrations.AddField(
            model_name='degree',
            name='campus_image_desktop',
            field=models.ImageField(blank=True, help_text='Provide a campus image to display on desktop displays', null=True, upload_to='media/degree_marketing/campus_images/'),
        ),
        migrations.AddField(
            model_name='degree',
            name='campus_image_mobile',
            field=models.ImageField(blank=True, help_text='Provide a campus image to display on mobile displays', null=True, upload_to='media/degree_marketing/campus_images/'),
        ),
        migrations.AddField(
            model_name='degree',
            name='campus_image_tablet',
            field=models.ImageField(blank=True, help_text='Provide a campus image to display on tablet displays', null=True, upload_to='media/degree_marketing/campus_images/'),
        ),
        migrations.AddField(
            model_name='degree',
            name='overall_ranking',
            field=models.CharField(blank=True, help_text='Overall program ranking (e.g. "#1 in the U.S.")', max_length=255),
        ),
        migrations.AlterModelOptions(
            name='degree',
            options={'verbose_name_plural': 'Degrees'},
        ),
    ]
