# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2022-12-19 07:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0090_auto_20220921_0844'),
        ('course_metadata', '0090_program_visibility'),
    ]

    operations = [
    ]
