# Generated by Django 1.11.11 on 2018-07-30 17:56


import django_extensions.db.fields
import sortedm2m.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0091_auto_20180727_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('rank', models.CharField(max_length=10, verbose_name='The actual rank number')),
                ('description', models.CharField(max_length=255, verbose_name='What does the rank number mean')),
                ('source', models.CharField(max_length=100, verbose_name='From where the rank is obtained')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
                'ordering': ('-modified', '-created'),
            },
        ),
        migrations.AddField(
            model_name='degree',
            name='rankings',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='course_metadata.Ranking'),
        ),
    ]
