# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2022-12-19 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0091_merge_20221219_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='card_image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='courserun',
            name='card_image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
