# Generated by Django 1.11.11 on 2018-08-02 16:52


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0092_auto_20180730_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculum',
            name='name',
        ),
        migrations.AddField(
            model_name='curriculum',
            name='marketing_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
