# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2023-01-04 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0092_auto_20221219_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courserun',
            name='short_description_override',
            field=models.TextField(blank=True, default=None, help_text="Short description specific for this run of a course. Leave this value blank to default to the parent course's short_description attribute.", null=True),
        ),
    ]
