# Generated by Django 1.11.11 on 2018-08-03 19:46


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0093_auto_20180802_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditpathway',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
