# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-03 14:59
from __future__ import unicode_literals

import django_extensions.db.fields
import sortedm2m.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0093_auto_20180802_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='IconTextPairing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('icon', models.CharField(max_length=100, verbose_name='Icon URL or fa class')),
                ('text', models.CharField(max_length=255, verbose_name='Paired text')),
            ],
            options={
                'abstract': False,
                'get_latest_by': 'modified',
                'ordering': ('-modified', '-created'),
            },
        ),
        migrations.AddField(
            model_name='degree',
            name='quick_facts',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='course_metadata.IconTextPairing'),
        ),
    ]
