# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2023-09-21 03:53
from __future__ import unicode_literals

import course_discovery.apps.course_metadata.models
from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0093_auto_20230104_0600'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='languages',
            field=course_discovery.apps.course_metadata.models.CommaSeparatedLanguagesField(blank=True, db_index=True, help_text='The ISO 639-2 language code for this language.', max_length=128, null=True),
        ),
    ]
