# Generated by Django 1.11.11 on 2018-08-06 15:14


import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0094_auto_20180803_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='IconTextPairing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('icon', models.CharField(max_length=100, verbose_name='Icon URL or fa class')),
                ('text', models.CharField(max_length=255, verbose_name='Paired text')),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_facts', to='course_metadata.Degree')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.AlterModelOptions(
            name='icontextpairing',
            options={'verbose_name_plural': 'IconTextPairings'},
        ),
        migrations.AlterField(
            model_name='icontextpairing',
            name='icon',
            field=models.CharField(
                choices=[('fa-award', 'Award'), ('fa-bell', 'Bell'), ('fa-certificate', 'Certificate'),
                         ('fa-check-circle', 'Checkmark'), ('fa-info-circle', 'Info'), ('fa-sitemap', 'Sitemap'),
                         ('fa-user', 'User'), ('fa-dollar', 'Dollar'), ('fa-book', 'Book'),
                         ('fa-mortar-board', 'Mortar Board')], max_length=100, verbose_name='Icon FA class'),
        ),

    ]
