# Generated by Django 1.11.11 on 2018-08-08 14:20


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0095_icontextpairing'),
    ]

    operations = [
        migrations.AddField(
            model_name='degree',
            name='lead_capture_list_name',
            field=models.CharField(blank=True, help_text='The sailthru email list name to capture leads', max_length=255, null=True),
        ),
    ]
