# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2025-05-06 12:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0096_auto_20250427_0241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='authoring_organizations',
        ),
        migrations.RemoveField(
            model_name='program',
            name='banner_image',
        ),
        migrations.RemoveField(
            model_name='program',
            name='banner_image_url',
        ),
        migrations.RemoveField(
            model_name='program',
            name='corporate_endorsements',
        ),
        migrations.RemoveField(
            model_name='program',
            name='credit_backing_organizations',
        ),
        migrations.RemoveField(
            model_name='program',
            name='credit_redemption_overview',
        ),
        migrations.RemoveField(
            model_name='program',
            name='excluded_course_runs',
        ),
        migrations.RemoveField(
            model_name='program',
            name='expected_learning_items',
        ),
        migrations.RemoveField(
            model_name='program',
            name='faq',
        ),
        migrations.RemoveField(
            model_name='program',
            name='hidden',
        ),
        migrations.RemoveField(
            model_name='program',
            name='individual_endorsements',
        ),
        migrations.RemoveField(
            model_name='program',
            name='instructor_ordering',
        ),
        migrations.RemoveField(
            model_name='program',
            name='job_outlook_items',
        ),
        migrations.RemoveField(
            model_name='program',
            name='marketing_slug',
        ),
        migrations.RemoveField(
            model_name='program',
            name='max_hours_effort_per_week',
        ),
        migrations.RemoveField(
            model_name='program',
            name='min_hours_effort_per_week',
        ),
        migrations.RemoveField(
            model_name='program',
            name='one_click_purchase_enabled',
        ),
        migrations.RemoveField(
            model_name='program',
            name='order_courses_by_start_date',
        ),
        migrations.RemoveField(
            model_name='program',
            name='overview',
        ),
        migrations.RemoveField(
            model_name='program',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='program',
            name='total_hours_of_effort',
        ),
        migrations.RemoveField(
            model_name='program',
            name='type',
        ),
        migrations.RemoveField(
            model_name='program',
            name='video',
        ),
        migrations.RemoveField(
            model_name='program',
            name='weeks_to_complete',
        ),
        migrations.RemoveField(
            model_name='program',
            name='language',
        ),
    ]
