# Generated by Django 1.11.15 on 2018-08-08 18:28


import django.db.models.deletion
import django_extensions.db.fields
import stdimage.models
from course_discovery.apps.course_metadata.utils import UploadToFieldNamePath
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0096_degree_lead_capture_list_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='degree',
            name='lead_capture_image',
            field=stdimage.models.StdImageField(blank=True, help_text='Please provide an image file for the lead capture banner.', null=True, upload_to=UploadToFieldNamePath('uuid', path='media/degree_marketing/lead_capture_images/')),
        ),
    ]
