# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-08 17:38
from __future__ import unicode_literals

import stdimage.models
import stdimage.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0096_degree_lead_capture_list_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='degree',
            name='lead_capture_image',
            field=stdimage.models.StdImageField(blank=True, help_text='Please provide an image file for the lead capture banner.', null=True, upload_to=stdimage.utils.UploadToAutoSlug('uuid', path='media/degree_marketing/lead_capture_images/')),
        ),
    ]
