# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2025-07-07 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0097_auto_20250506_1208'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseentitlement',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='courseentitlement',
            name='course',
        ),
        migrations.RemoveField(
            model_name='courseentitlement',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='courseentitlement',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='courseentitlement',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='program',
            name='partner',
        ),
        migrations.AddField(
            model_name='course',
            name='org',
            field=models.CharField(db_index=True, help_text='A organization name', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='orgs',
            field=models.CharField(db_index=True, help_text='This field should include all Organizations used by the site. E.g.: orgA+orgB+orgC', max_length=128, null=True),
        ),
        migrations.RemoveField(
            model_name='course',
            name='partner',
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set([('org', 'key'), ('org', 'uuid')]),
        ),
        migrations.DeleteModel(
            name='CourseEntitlement',
        ),
    ]
