# Generated by Django 1.11.15 on 2018-08-09 15:33


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0098_degree_cost_and_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='degree',
            name='micromasters_long_description',
            field=models.TextField(blank=True, help_text='Micromasters descriptive paragraph', null=True),
        ),
        migrations.AddField(
            model_name='degree',
            name='micromasters_long_title',
            field=models.CharField(blank=True, help_text='Micromasters verbose title', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='degree',
            name='micromasters_url',
            field=models.URLField(blank=True, help_text='URL to micromasters landing page', max_length=255, null=True),
        ),
    ]
