# Generated by Django 1.11.15 on 2018-08-15 20:17


import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0100_details_fine_print'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditpathway',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, null=True, verbose_name='UUID'),
        ),
    ]
