# Generated by Django 1.11.15 on 2018-08-15 20:17


import uuid
from django.db import migrations

def gen_uuid(apps, schema_editor):
    CreditPathway = apps.get_model('course_metadata', 'CreditPathway')
    for pathway in CreditPathway.objects.all():
        pathway.uuid = uuid.uuid4()
        pathway.save(update_fields=['uuid'])

class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0101_auto_20180815_2017'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, migrations.RunPython.noop),
    ]
