# Generated by Django 1.11.15 on 2018-08-15 20:17


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0103_auto_20180815_2017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditpathway',
            options={'get_latest_by': 'modified', 'ordering': ('-modified', '-created')},
        ),
        migrations.AlterUniqueTogether(
            name='creditpathway',
            unique_together=set(),
        ),
    ]
