# Generated by Django 1.11.15 on 2018-08-17 17:54


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0104_auto_20180815_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degree',
            name='application_requirements',
            field=models.TextField(default='TBD'),
        ),
        migrations.AlterField(
            model_name='degree',
            name='prerequisite_coursework',
            field=models.TextField(default='TBD'),
        ),
    ]
