# Generated by Django 1.11.11 on 2018-08-20 17:57


from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import sortedm2m.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20171004_1133'),
        ('course_metadata', '0105_auto_20180817_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pathway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('name', models.CharField(max_length=255)),
                ('org_name', models.CharField(max_length=255, verbose_name='Organization name')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('description', models.TextField(blank=True, null=True)),
                ('destination_url', models.URLField(blank=True, null=True)),
                ('partner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Partner')),
                ('programs', sortedm2m.fields.SortedManyToManyField(help_text=None, to='course_metadata.Program')),
            ],
            options={
                'abstract': False,
                'get_latest_by': 'modified',
                'ordering': ('-modified', '-created'),
            },
        ),
    ]
