# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-20 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0105_auto_20180817_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='degree',
            name='campus_image_desktop',
        ),
        migrations.RemoveField(
            model_name='degree',
            name='campus_image_mobile',
        ),
        migrations.RemoveField(
            model_name='degree',
            name='campus_image_tablet',
        ),
        migrations.AddField(
            model_name='degree',
            name='campus_image',
            field=models.ImageField(blank=True, help_text='Provide a campus image for the header of the degree', null=True, upload_to='media/degree_marketing/campus_images/'),
        ),
        migrations.AddField(
            model_name='degree',
            name='title_background_image',
            field=models.ImageField(blank=True, help_text='Provide a background image for the title section of the degree', null=True, upload_to='media/degree_marketing/campus_images'),
        ),
    ]
