# Generated by Django 1.11.15 on 2018-08-21 13:40


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0106_pathway'),
    ]

    operations = [
        migrations.AddField(
            model_name='degree',
            name='campus_image',
            field=models.ImageField(blank=True, help_text='Provide a campus image for the header of the degree', null=True, upload_to='media/degree_marketing/campus_images/'),
        ),
        migrations.AddField(
            model_name='degree',
            name='title_background_image',
            field=models.ImageField(blank=True, help_text='Provide a background image for the title section of the degree', null=True, upload_to='media/degree_marketing/campus_images/'),
        ),
    ]
