# Generated by Django 1.11.15 on 2018-08-22 16:24


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0108_auto_20180822_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='degree',
            name='search_card_cost',
            field=models.CharField(blank=True, help_text='Cost display for search card (e.g. "$9,999"', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='degree',
            name='search_card_courses',
            field=models.CharField(blank=True, help_text='Number of courses for search card (e.g. "11 Courses"', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='degree',
            name='search_card_ranking',
            field=models.CharField(blank=True, help_text='Ranking display for search card (e.g. "#1 in the U.S."', max_length=50, null=True),
        ),
    ]
