# Generated by Django 1.11.15 on 2018-08-24 17:27


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0109_auto_20180822_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditpathway',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='creditpathway',
            name='programs',
        ),
        migrations.DeleteModel(
            name='CreditPathway',
        ),
    ]
