# Generated by Django 1.11.15 on 2018-08-29 01:41


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0111_pathway_pathway_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='degree',
            name='banner_border_color',
            field=models.CharField(blank=True, help_text='The 6 character hex value of the color to make the banner borders (e.g. "#ff0000" which equals red) No need to provide the `#`', max_length=6),
        ),
    ]
