# Generated by Django 1.11.15 on 2018-09-05 15:47


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0113_brief_text_curriculum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='degree',
            name='campus_image_desktop',
        ),
        migrations.RemoveField(
            model_name='degree',
            name='campus_image_mobile',
        ),
        migrations.RemoveField(
            model_name='degree',
            name='campus_image_tablet',
        ),
    ]
