# Generated by Django 1.11.15 on 2018-09-07 15:51


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0114_auto_20180905_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='marketing_text_brief',
            field=models.TextField(blank=True, help_text='A high-level overview of the degree\'s courseware. The "brief"\n            text is the first 750 characters of "marketing_text" and must be\n            valid HTML.', max_length=750, null=True),
        ),
    ]
