# Generated by Django 1.11.15 on 2018-09-26 14:42


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0119_auto_20180925_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icontextpairing',
            name='icon',
            field=models.CharField(choices=[('fa-bell', 'Bell'), ('fa-certificate', 'Certificate'), ('fa-check-circle', 'Checkmark'), ('fa-clock-o', 'Clock'), ('fa-desktop', 'Desktop'), ('fa-info-circle', 'Info'), ('fa-sitemap', 'Sitemap'), ('fa-user', 'User'), ('fa-dollar', 'Dollar'), ('fa-book', 'Book'), ('fa-mortar-board', 'Mortar Board'), ('fa-star', 'Star'), ('fa-trophy', 'Trophy')], max_length=100, verbose_name='Icon FA class'),
        ),
    ]
