# Generated by Django 1.11.15 on 2018-09-26 16:04


import course_discovery.apps.course_metadata.utils
from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0120_auto_20180926_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degree',
            name='lead_capture_image',
            field=stdimage.models.StdImageField(blank=True, help_text='Please provide an image file for the lead capture banner.', null=True, upload_to=course_discovery.apps.course_metadata.utils.UploadToFieldNamePath('uuid', path='media/degree_marketing/lead_capture_images/')),
        ),
        migrations.AlterField(
            model_name='degree',
            name='micromasters_background_image',
            field=stdimage.models.StdImageField(blank=True, help_text='Customized background image for the MicroMasters section.', null=True, upload_to=course_discovery.apps.course_metadata.utils.UploadToFieldNamePath('uuid', path='media/degree_marketing/mm_images/')),
        ),
    ]
