# Generated by Django 1.11.15 on 2018-09-24 15:33


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ietf_language_tags', '0001_squashed_0005_fix_language_tag_names_again'),
        ('course_metadata', '0121_degree_image_naming'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='bio_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ietf_language_tags.LanguageTag'),
        ),
    ]
