# Generated by Django 1.11.15 on 2018-10-26 14:09


from django.db import migrations, models


def migrate_learner_testimonials_to_cm_course(apps, schema_editor):
    CM_Course = apps.get_model('course_metadata', 'Course')
    CM_CourseRun = apps.get_model('course_metadata', 'CourseRun')
    for course_run in CM_CourseRun.objects.all():
        # Only care if there are learner testimonials
        if course_run.learner_testimonials:
            # Grab the corresponding course in course_metadata
            cm_course = CM_Course.objects.get(id=course_run.course_id)
            if not cm_course.learner_testimonials:
                # Grab all course runs ordered by descending start date
                all_course_runs = CM_CourseRun.objects.filter(course_id=course_run.course_id).order_by('-start')
                # Starting from the most recent course run, try and assign the course the learner testimonials
                # If the most recent one does not contain LTs, then keep trying until you find the most recent one
                # that does.
                for most_recent_course_run in all_course_runs:
                    if most_recent_course_run.learner_testimonials:
                        cm_course.learner_testimonials = most_recent_course_run.learner_testimonials
                        cm_course.save()
                        break


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0123_auto_20181003_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='faq',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='FAQ'),
        ),
        migrations.AddField(
            model_name='course',
            name='learner_testimonials',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.RunPython(migrate_learner_testimonials_to_cm_course),
    ]
