# Generated by Django 1.11.15 on 2018-11-06 18:04


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0125_course_additional_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='has_ofac_restrictions',
            field=models.BooleanField(default=False, verbose_name='Course Has OFAC Restrictions'),
        ),
    ]
