# Generated by Django 1.11.15 on 2018-11-07 17:16


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0126_course_has_ofac_restrictions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courserun',
            name='learner_testimonials',
        ),
    ]
