# Generated by Django 1.11.15 on 2018-11-26 19:29


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0127_remove_courserun_learner_testimonials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='key',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
