# Generated by Django 1.11.15 on 2018-11-13 14:15


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0128_auto_20181126_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courserun',
            name='short_description_override',
            field=models.TextField(blank=True, default=None, help_text="Short description specific for this run of a course. Leave this value blank to default to the parent course's short_description attribute.", null=True),
        ),
    ]
