# Generated by Django 1.11.15 on 2018-11-21 14:32


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0130_courserun_has_ofac_restrictions'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='major_works',
            field=models.TextField(blank=True, help_text='A list of major works by this person. Must be valid HTML.'),
        ),
    ]
