# Generated by Django 1.11.15 on 2018-11-21 14:39


from django.db import migrations


def move_works(apps, _schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Person = apps.get_model('course_metadata', 'Person')
    PersonWork = apps.get_model('course_metadata', 'PersonWork')
    for person in Person.objects.all():
        works = PersonWork.objects.filter(person=person)
        person.major_works = '<br/>\n'.join(work.value for work in works)
        person.save()


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0131_person_major_works'),
    ]

    operations = [
        migrations.RunPython(move_works),
    ]
