# Generated by Django 1.11.15 on 2018-11-20 20:29


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0132_person_works_to_major_works'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courserunsocialnetwork',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='courserunsocialnetwork',
            name='course_run',
        ),
        migrations.RenameField(
            model_name='personsocialnetwork',
            old_name='value',
            new_name='url',
        ),
        migrations.AddField(
            model_name='personsocialnetwork',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='personsocialnetwork',
            unique_together={('person', 'type', 'title')},
        ),
        migrations.DeleteModel(
            name='CourseRunSocialNetwork',
        ),
    ]
