# Generated by Django 1.11.15 on 2018-12-03 20:56


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0133_remove_courserun_social_network_and_add_title_to_person_socialnetwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletePersonDupsConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arguments', models.TextField(blank=True, default='', help_text='Useful for manually running a Jenkins job. Specify like "--partner-code=edx A:B C:D".')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'delete_person_dups argument',
            },
        ),
    ]
