# Generated by Django 1.11.15 on 2018-12-05 15:54


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0134_add_delete_person_dups_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personwork',
            name='person',
        ),
        migrations.AlterField(
            model_name='personsocialnetwork',
            name='type',
            field=models.CharField(choices=[('blog', 'Blog'), ('facebook', 'Facebook'), ('others', 'Others'), ('twitter', 'Twitter')], db_index=True, max_length=15),
        ),
        migrations.DeleteModel(
            name='PersonWork',
        ),
    ]
