# Generated by Django 1.11.15 on 2018-12-05 21:12


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0135_remove_personwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrupalPublishUuidConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_run_ids', models.TextField(default=None, verbose_name='Course Run IDs')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
