# Generated by Django 1.11.15 on 2018-12-12 13:50


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0137_personareaofexpertise'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileImageDownloadConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_uuids', models.TextField(default=None, verbose_name='Profile Image UUIDs')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
