# Generated by Django 1.11.15 on 2018-12-21 15:01


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0140_remove_profile_url_and_fix_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='enrollment_count',
            field=models.IntegerField(default=0, help_text='Total number of learners who have enrolled in this course'),
        ),
        migrations.AddField(
            model_name='course',
            name='recent_enrollment_count',
            field=models.IntegerField(default=0, help_text='Total number of learners who have enrolled in this course in the last 6 months'),
        ),
        migrations.AddField(
            model_name='courserun',
            name='enrollment_count',
            field=models.IntegerField(default=0, help_text='Total number of learners who have enrolled in this course run'),
        ),
        migrations.AddField(
            model_name='courserun',
            name='recent_enrollment_count',
            field=models.IntegerField(default=0, help_text='Total number of learners who have enrolled in this course run in the last 6 months'),
        ),
        migrations.AddField(
            model_name='program',
            name='enrollment_count',
            field=models.IntegerField(default=0, help_text='Total number of learners who have enrolled in courses this program'),
        ),
        migrations.AddField(
            model_name='program',
            name='recent_enrollment_count',
            field=models.IntegerField(default=0, help_text='Total number of learners who have enrolled in courses in this program in the last 6 months'),
        ),
    ]
