# Generated by Django 1.11.15 on 2018-12-26 20:29


from django.db import migrations, models
import taggit_autosuggest.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('course_metadata', '0141_auto_20181221_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='topics',
            field=taggit_autosuggest.managers.TaggableManager(blank=True, help_text='Pick a tag from the suggestions. To make a new tag, add a comma after the tag name.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='course',
            name='enrollment_count',
            field=models.IntegerField(blank=True, default=0, help_text='Total number of learners who have enrolled in this course', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='recent_enrollment_count',
            field=models.IntegerField(blank=True, default=0, help_text='Total number of learners who have enrolled in this course in the last 6 months', null=True),
        ),
        migrations.AlterField(
            model_name='courserun',
            name='enrollment_count',
            field=models.IntegerField(blank=True, default=0, help_text='Total number of learners who have enrolled in this course run', null=True),
        ),
        migrations.AlterField(
            model_name='courserun',
            name='recent_enrollment_count',
            field=models.IntegerField(blank=True, default=0, help_text='Total number of learners who have enrolled in this course run in the last 6 months', null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='enrollment_count',
            field=models.IntegerField(blank=True, default=0, help_text='Total number of learners who have enrolled in courses this program', null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='recent_enrollment_count',
            field=models.IntegerField(blank=True, default=0, help_text='Total number of learners who have enrolled in courses in this program in the last 6 months', null=True),
        ),
    ]
