# Generated by Django 1.11.15 on 2019-01-02 14:29


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0142_auto_20181226_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='profile_image_url',
        ),
    ]
