# Generated by Django 1.11.15 on 2018-12-19 21:09


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0143_remove_person_profile_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
