# Generated by Django 1.11.15 on 2019-01-17 20:18


from django.db import migrations


def delete_switch(apps, schema_editor):
    """ Delete the log_course_search_queries switch. """
    Switch = apps.get_model('waffle', 'Switch')
    Switch.objects.filter(name='log_course_search_queries').delete()

def create_switch(apps, schema_editor):
    """ Create the log_course_search_queries switch if it does not already exist. """
    Switch = apps.get_model('waffle', 'Switch')
    Switch.objects.get_or_create(name='log_course_search_queries', defaults={'active': False})


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0145_courserun_autoslug'),
        ('waffle', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(delete_switch, create_switch),
    ]
