# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-09 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0145_courserun_autoslug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courserun',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
