# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-23 17:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0146_degree_hubspot_lead_capture_form_id'),
        ('course_metadata', '0146_remove_log_queries_switch'),
    ]

    operations = [
    ]
