# Generated by Django 1.11.15 on 2019-02-01 15:15


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0148_auto_20190131_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degreedeadline',
            name='time',
            field=models.CharField(blank=True, help_text='The time after which the deadline expires (e.g. 11:59 PM EST).', max_length=255),
        ),
    ]
