# Generated by Django 1.11.15 on 2019-02-06 18:35


from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0151_remove_curriculum_degree'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumCourseMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_metadata.Course')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_metadata.Curriculum')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CurriculumProgramMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_metadata.Curriculum')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_metadata.Program')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
