# Generated by Django 1.11.15 on 2019-02-06 20:49


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0152_curriculumcoursemembership_curriculumprogrammembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='course_curriculum',
            field=models.ManyToManyField(related_name='degree_course_curricula', through='course_metadata.CurriculumCourseMembership', to='course_metadata.Course'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='program_curriculum',
            field=models.ManyToManyField(related_name='degree_program_curricula', through='course_metadata.CurriculumProgramMembership', to='course_metadata.Program'),
        ),
    ]
