# Generated by Django 1.11.15 on 2019-02-07 15:46


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0154_course_entitlement_default_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='degreecoursecurriculum',
            name='course',
        ),
        migrations.RemoveField(
            model_name='degreecoursecurriculum',
            name='curriculum',
        ),
        migrations.RemoveField(
            model_name='degreeprogramcurriculum',
            name='curriculum',
        ),
        migrations.RemoveField(
            model_name='degreeprogramcurriculum',
            name='program',
        ),
        migrations.DeleteModel(
            name='DegreeCourseCurriculum',
        ),
        migrations.DeleteModel(
            name='DegreeProgramCurriculum',
        ),
    ]
