# Generated by Django 1.11.15 on 2019-02-08 20:13


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0156_add_curriculum_name_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumcoursemembership',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='curriculumprogrammembership',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
