# Generated by Django 1.11.15 on 2019-02-11 17:48


from django.db import migrations, models


def set_initial_order(apps, _schema_editor):
    LevelType = apps.get_model('course_metadata', 'LevelType')
    order = 0
    for item in LevelType.objects.all().order_by('id'):
        order += 1
        item.order = order
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0157_curriculum_membership_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leveltype',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='leveltype',
            name='order',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
        migrations.RunPython(set_initial_order, reverse_code=migrations.RunPython.noop),
    ]
