# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-14 19:49
from __future__ import unicode_literals

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0161_curriculum_course_run_exclusions'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='authoring_organizations',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, to='course_metadata.Organization'),
        ),
    ]
