# Generated by Django 1.11.15 on 2019-03-22 19:17


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_partner_lms_commerce_api_url'),
        ('course_metadata', '0162_auto_20190318_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='src',
            field=models.URLField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='src',
            field=models.URLField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='image',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together={('partner', 'uuid')},
        ),
        migrations.AlterUniqueTogether(
            name='video',
            unique_together=set(),
        ),
    ]
