# Generated by Django 1.11.15 on 2019-04-01 19:26


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0164_drop_draft_field_video_image_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='draft_version',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='official_version', to='course_metadata.Course'),
        ),
        migrations.AddField(
            model_name='courseentitlement',
            name='draft_version',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='official_version', to='course_metadata.CourseEntitlement'),
        ),
        migrations.AddField(
            model_name='courserun',
            name='draft_version',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='official_version', to='course_metadata.CourseRun'),
        ),
        migrations.AddField(
            model_name='seat',
            name='draft_version',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='official_version', to='course_metadata.Seat'),
        ),
    ]
