# Generated by Django 1.11.15 on 2019-04-03 16:06


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0166_draft_version_is_blankable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculumcoursemembership',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_course_membership', to='course_metadata.Course'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='type',
            field=models.CharField(choices=[('honor', 'Honor'), ('audit', 'Audit'), ('verified', 'Verified'), ('professional', 'Professional'), ('credit', 'Credit'), ('masters', 'Masters')], max_length=63),
        ),
    ]
