# Generated by Django 1.11.15 on 2019-04-04 17:33


from django.db import migrations, models
import django.db.models.manager
import djchoices.choices


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0167_auto_20190403_1606'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='course',
            managers=[
                ('everything', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='courseentitlement',
            managers=[
                ('everything', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='courserun',
            managers=[
                ('everything', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='seat',
            managers=[
                ('everything', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='courserun',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('unpublished', 'Unpublished'), ('reviewed', 'Reviewed'), ('review_by_legal', 'Awaiting Review from Legal'), ('review_by_internal', 'Awaiting Internal Review')], db_index=True, default='unpublished', max_length=255, validators=[djchoices.choices.ChoicesValidator({'published': 'Published', 'review_by_internal': 'Awaiting Internal Review', 'review_by_legal': 'Awaiting Review from Legal', 'reviewed': 'Reviewed', 'unpublished': 'Unpublished'})]),
        ),
    ]
