# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-16 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0169_rename_official_version'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['id', 'draft'], name='course_meta_id_d4c695_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['id', 'draft_version_id'], name='course_meta_id_7adf4c_idx'),
        ),
        migrations.AddIndex(
            model_name='courseentitlement',
            index=models.Index(fields=['id', 'draft'], name='course_meta_id_5c815d_idx'),
        ),
        migrations.AddIndex(
            model_name='courseentitlement',
            index=models.Index(fields=['id', 'draft_version_id'], name='course_meta_id_5ca6e2_idx'),
        ),
        migrations.AddIndex(
            model_name='seat',
            index=models.Index(fields=['id', 'draft'], name='course_meta_id_b237e4_idx'),
        ),
        migrations.AddIndex(
            model_name='seat',
            index=models.Index(fields=['id', 'draft_version_id'], name='course_meta_id_726780_idx'),
        ),
        migrations.AddIndex(
            model_name='courserun',
            index=models.Index(fields=['id', 'draft'], name='course_meta_id_a0dbd0_idx'),
        ),
        migrations.AddIndex(
            model_name='courserun',
            index=models.Index(fields=['id', 'draft_version_id'], name='course_meta_id_30a1e9_idx'),
        ),
    ]
