# Generated by Django 1.11.15 on 2019-05-01 17:07


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0172_historicalcourse'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseentitlement',
            unique_together={('course', 'draft')},
        ),
    ]
