# Generated by Django 1.11.15 on 2019-05-02 14:20


from django.db import migrations, models
import djchoices.choices


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0173_course_entitlement_unique_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courserun',
            name='status',
            field=models.CharField(choices=[('unpublished', 'Unpublished'), ('review_by_legal', 'Awaiting Review from Legal'), ('review_by_internal', 'Awaiting Internal Review'), ('reviewed', 'Reviewed'), ('published', 'Published')], db_index=True, default='unpublished', max_length=255, validators=[djchoices.choices.ChoicesValidator({'published': 'Published', 'review_by_internal': 'Awaiting Internal Review', 'review_by_legal': 'Awaiting Review from Legal', 'reviewed': 'Reviewed', 'unpublished': 'Unpublished'})]),
        ),
        migrations.AlterField(
            model_name='historicalcourserun',
            name='status',
            field=models.CharField(choices=[('unpublished', 'Unpublished'), ('review_by_legal', 'Awaiting Review from Legal'), ('review_by_internal', 'Awaiting Internal Review'), ('reviewed', 'Reviewed'), ('published', 'Published')], db_index=True, default='unpublished', max_length=255, validators=[djchoices.choices.ChoicesValidator({'published': 'Published', 'review_by_internal': 'Awaiting Internal Review', 'review_by_legal': 'Awaiting Review from Legal', 'reviewed': 'Reviewed', 'unpublished': 'Unpublished'})]),
        ),
    ]
