# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-01 17:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0173_historicalcourse'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseentitlement',
            unique_together=set([('course', 'draft')]),
        ),
    ]
