# Generated by Django 1.11.15 on 2019-05-20 20:21


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0174_reorder_course_run_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='degree',
            name='micromasters_org_name_override',
            field=models.CharField(blank=True, help_text='Override org name if micromasters program comes from different organization than Masters program', max_length=50, null=True),
        ),
    ]
