# Generated by Django 1.11.15 on 2019-05-22 14:12


import course_discovery.apps.course_metadata.fields
import course_discovery.apps.course_metadata.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0175_degree_micromasters_org_name_override'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='additional_information',
            field=course_discovery.apps.course_metadata.fields.NullHtmlField(blank=True, default=None, null=True, validators=[course_discovery.apps.course_metadata.validators.validate_html], verbose_name='Additional Information'),
        ),
        migrations.AlterField(
            model_name='course',
            name='faq',
            field=course_discovery.apps.course_metadata.fields.NullHtmlField(blank=True, default=None, null=True, validators=[course_discovery.apps.course_metadata.validators.validate_html], verbose_name='FAQ'),
        ),
        migrations.AlterField(
            model_name='course',
            name='full_description',
            field=course_discovery.apps.course_metadata.fields.NullHtmlField(blank=True, default=None, null=True, validators=[course_discovery.apps.course_metadata.validators.validate_html]),
        ),
        migrations.AlterField(
            model_name='course',
            name='learner_testimonials',
            field=course_discovery.apps.course_metadata.fields.NullHtmlField(blank=True, default=None, null=True, validators=[course_discovery.apps.course_metadata.validators.validate_html]),
        ),
        migrations.AlterField(
            model_name='course',
            name='outcome',
            field=course_discovery.apps.course_metadata.fields.NullHtmlField(blank=True, default=None, null=True, validators=[course_discovery.apps.course_metadata.validators.validate_html]),
        ),
        migrations.AlterField(
            model_name='course',
            name='prerequisites_raw',
            field=course_discovery.apps.course_metadata.fields.NullHtmlField(blank=True, default=None, null=True, validators=[course_discovery.apps.course_metadata.validators.validate_html]),
        ),
        migrations.AlterField(
            model_name='course',
            name='short_description',
            field=course_discovery.apps.course_metadata.fields.NullHtmlField(blank=True, default=None, null=True, validators=[course_discovery.apps.course_metadata.validators.validate_html]),
        ),
        migrations.AlterField(
            model_name='course',
            name='syllabus_raw',
            field=course_discovery.apps.course_metadata.fields.NullHtmlField(blank=True, default=None, null=True, validators=[course_discovery.apps.course_metadata.validators.validate_html]),
        ),
        migrations.AlterField(
            model_name='courserun',
            name='full_description_override',
            field=course_discovery.apps.course_metadata.fields.NullHtmlField(blank=True, default=None, help_text="Full description specific for this run of a course. Leave this value blank to default to the parent course's full_description attribute.", null=True, validators=[course_discovery.apps.course_metadata.validators.validate_html]),
        ),
        migrations.AlterField(
            model_name='courserun',
            name='outcome_override',
            field=course_discovery.apps.course_metadata.fields.NullHtmlField(blank=True, default=None, help_text="'What You Will Learn' description for this particular course run. Leave this value blank to default to the parent course's Outcome attribute.", null=True, validators=[course_discovery.apps.course_metadata.validators.validate_html]),
        ),
        migrations.AlterField(
            model_name='courserun',
            name='short_description_override',
            field=course_discovery.apps.course_metadata.fields.NullHtmlField(blank=True, default=None, help_text="Short description specific for this run of a course. Leave this value blank to default to the parent course's short_description attribute.", null=True, validators=[course_discovery.apps.course_metadata.validators.validate_html]),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='marketing_text',
            field=course_discovery.apps.course_metadata.fields.HtmlField(help_text="A high-level overview of the degree's courseware.", null=True, validators=[course_discovery.apps.course_metadata.validators.validate_html]),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='marketing_text_brief',
            field=course_discovery.apps.course_metadata.fields.NullHtmlField(blank=True, default=None, help_text='A high-level overview of the degree\'s courseware. The "brief"\n            text is the first 750 characters of "marketing_text" and must be\n            valid HTML.', max_length=750, null=True, validators=[course_discovery.apps.course_metadata.validators.validate_html]),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='additional_information',
            field=course_discovery.apps.course_metadata.fields.NullHtmlField(blank=True, default=None, null=True, validators=[course_discovery.apps.course_metadata.validators.validate_html], verbose_name='Additional Information'),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='faq',
            field=course_discovery.apps.course_metadata.fields.NullHtmlField(blank=True, default=None, null=True, validators=[course_discovery.apps.course_metadata.validators.validate_html], verbose_name='FAQ'),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='full_description',
            field=course_discovery.apps.course_metadata.fields.NullHtmlField(blank=True, default=None, null=True, validators=[course_discovery.apps.course_metadata.validators.validate_html]),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='learner_testimonials',
            field=course_discovery.apps.course_metadata.fields.NullHtmlField(blank=True, default=None, null=True, validators=[course_discovery.apps.course_metadata.validators.validate_html]),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='outcome',
            field=course_discovery.apps.course_metadata.fields.NullHtmlField(blank=True, default=None, null=True, validators=[course_discovery.apps.course_metadata.validators.validate_html]),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='prerequisites_raw',
            field=course_discovery.apps.course_metadata.fields.NullHtmlField(blank=True, default=None, null=True, validators=[course_discovery.apps.course_metadata.validators.validate_html]),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='short_description',
            field=course_discovery.apps.course_metadata.fields.NullHtmlField(blank=True, default=None, null=True, validators=[course_discovery.apps.course_metadata.validators.validate_html]),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='syllabus_raw',
            field=course_discovery.apps.course_metadata.fields.NullHtmlField(blank=True, default=None, null=True, validators=[course_discovery.apps.course_metadata.validators.validate_html]),
        ),
        migrations.AlterField(
            model_name='historicalcourserun',
            name='full_description_override',
            field=course_discovery.apps.course_metadata.fields.NullHtmlField(blank=True, default=None, help_text="Full description specific for this run of a course. Leave this value blank to default to the parent course's full_description attribute.", null=True, validators=[course_discovery.apps.course_metadata.validators.validate_html]),
        ),
        migrations.AlterField(
            model_name='historicalcourserun',
            name='outcome_override',
            field=course_discovery.apps.course_metadata.fields.NullHtmlField(blank=True, default=None, help_text="'What You Will Learn' description for this particular course run. Leave this value blank to default to the parent course's Outcome attribute.", null=True, validators=[course_discovery.apps.course_metadata.validators.validate_html]),
        ),
        migrations.AlterField(
            model_name='historicalcourserun',
            name='short_description_override',
            field=course_discovery.apps.course_metadata.fields.NullHtmlField(blank=True, default=None, help_text="Short description specific for this run of a course. Leave this value blank to default to the parent course's short_description attribute.", null=True, validators=[course_discovery.apps.course_metadata.validators.validate_html]),
        ),
        migrations.AlterField(
            model_name='historicalcurriculum',
            name='marketing_text',
            field=course_discovery.apps.course_metadata.fields.HtmlField(help_text="A high-level overview of the degree's courseware.", null=True, validators=[course_discovery.apps.course_metadata.validators.validate_html]),
        ),
        migrations.AlterField(
            model_name='historicalcurriculum',
            name='marketing_text_brief',
            field=course_discovery.apps.course_metadata.fields.NullHtmlField(blank=True, default=None, help_text='A high-level overview of the degree\'s courseware. The "brief"\n            text is the first 750 characters of "marketing_text" and must be\n            valid HTML.', max_length=750, null=True, validators=[course_discovery.apps.course_metadata.validators.validate_html]),
        ),
        migrations.AlterField(
            model_name='person',
            name='bio',
            field=course_discovery.apps.course_metadata.fields.NullHtmlField(blank=True, default=None, null=True, validators=[course_discovery.apps.course_metadata.validators.validate_html]),
        ),
        migrations.AlterField(
            model_name='person',
            name='major_works',
            field=course_discovery.apps.course_metadata.fields.HtmlField(blank=True, help_text='A list of major works by this person. Must be valid HTML.', validators=[course_discovery.apps.course_metadata.validators.validate_html]),
        ),
    ]
