# Generated by Django 1.11.21 on 2019-06-06 18:58


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0177_historicalprogram_historicalprogramtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserun',
            name='external_key',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='historicalcourserun',
            name='external_key',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
