# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-13 17:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0181_auto_20190613_1440'),
        ('course_metadata', '0179_tagcourseuuidsconfig'),
    ]

    operations = [
    ]
