# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-14 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0182_merge_20190613_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagcourseuuidsconfig',
            name='course_uuids',
            field=models.TextField(default=None, null=True, verbose_name='Course UUIDs'),
        ),
        migrations.AlterField(
            model_name='tagcourseuuidsconfig',
            name='tag',
            field=models.TextField(default=None, null=True, verbose_name='Tag'),
        ),
    ]
