# Generated by Django 1.11.21 on 2019-06-11 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0182_tagcourseuuidsconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserun',
            name='expected_program_name',
            field=models.CharField(default='', max_length=255, blank=True),
        ),
        migrations.AddField(
            model_name='courserun',
            name='expected_program_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='course_metadata.ProgramType'),
        ),
        migrations.AddField(
            model_name='historicalcourserun',
            name='expected_program_name',
            field=models.CharField(default='', max_length=255, blank=True),
        ),
        migrations.AddField(
            model_name='historicalcourserun',
            name='expected_program_type',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='course_metadata.ProgramType'),
        ),
    ]
