# Generated by Django 1.11.21 on 2019-07-10 16:11


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0184_migratecourseeditorsconfig'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MigrateCourseEditorsConfig',
            new_name='MigratePublisherToCourseMetadataConfig',
        ),
    ]
