# Generated by Django 1.11.22 on 2019-07-15 17:12


from django.db import migrations, models
import django.db.models.deletion
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_lms_admin_url'),
        ('course_metadata', '0185_migrate_publisher_to_course_metadata_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='migratepublishertocoursemetadataconfig',
            name='org_keys',
        ),
        migrations.AddField(
            model_name='migratepublishertocoursemetadataconfig',
            name='orgs',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='course_metadata.Organization'),
        ),
        migrations.AddField(
            model_name='migratepublishertocoursemetadataconfig',
            name='partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Partner'),
        ),
    ]
