# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-10 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0185_migratecourseeditorsconfig'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MigrateCourseEditorsConfig',
            new_name='MigratePublisherToCourseMetadataConfig',
        ),
    ]
