# Generated by Django 1.11.22 on 2019-08-02 17:06


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0186_update_migrate_publisher_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserun',
            name='ofac_comment',
            field=models.TextField(blank=True, help_text='Comment related to OFAC restriction'),
        ),
        migrations.AddField(
            model_name='historicalcourserun',
            name='ofac_comment',
            field=models.TextField(blank=True, help_text='Comment related to OFAC restriction'),
        ),
        migrations.AlterField(
            model_name='courserun',
            name='has_ofac_restrictions',
            field=models.NullBooleanField(choices=[('', '--'), (True, 'Restricted'), (False, 'Not restricted')], default=None, verbose_name='Add OFAC restriction text to the FAQ section of the Marketing site'),
        ),
        migrations.AlterField(
            model_name='historicalcourserun',
            name='has_ofac_restrictions',
            field=models.NullBooleanField(choices=[('', '--'), (True, 'Restricted'), (False, 'Not restricted')], default=None, verbose_name='Add OFAC restriction text to the FAQ section of the Marketing site'),
        ),
    ]
