# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-08 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0187_update_course_run_ofac_add_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='seattype',
            name='certificate_type',
            field=models.CharField(blank=True, choices=[('honor', 'honor'), ('credit', 'credit'), ('verified', 'verified'), ('professional', 'professional')], default='', help_text='Certificate type granted if this mode is eligible for a certificate, or blank if not.', max_length=64),
        ),
        migrations.AddField(
            model_name='seattype',
            name='is_credit_eligible',
            field=models.BooleanField(default=False, help_text="Completion can impart credit toward a partner institution's degree."),
        ),
        migrations.AddField(
            model_name='seattype',
            name='is_id_verified',
            field=models.BooleanField(default=False, help_text='This mode requires ID verification.'),
        ),
        migrations.AddField(
            model_name='seattype',
            name='is_paid_to_partner',
            field=models.BooleanField(default=False, help_text='This mode is one that is paid to a partner, e.g. a masters course paid to the school.'),
        ),
        migrations.AddField(
            model_name='seattype',
            name='is_paid_to_platform',
            field=models.BooleanField(default=False, help_text='This mode is one that is paid to the current platform operator.'),
        ),
    ]
