# Generated by Django 1.11.23 on 2019-08-13 21:09


from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0187_update_course_run_ofac_add_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='url_slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, help_text='Leave this field blank to have the value generated automatically.', populate_from='title'),
        ),
    ]
