# Generated by Django 1.11.22 on 2019-07-30 18:13


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0188_course_url_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='salesforce_case_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='salesforce_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='courserun',
            name='salesforce_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='salesforce_case_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='salesforce_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalcourserun',
            name='salesforce_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='salesforce_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
