# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-26 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_case_record_type_id'),
        ('course_metadata', '0191_add_microbachelors_program_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='draft_version',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_official_version', to='course_metadata.Course'),
        ),
        migrations.AlterField(
            model_name='courseentitlement',
            name='draft_version',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_official_version', to='course_metadata.CourseEntitlement'),
        ),
        migrations.AlterField(
            model_name='courserun',
            name='draft_version',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_official_version', to='course_metadata.CourseRun'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='draft_version',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_official_version', to='course_metadata.Seat'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set([('partner', 'uuid', 'draft'), ('url_slug', 'draft'), ('partner', 'key', 'draft')]),
        ),
    ]
