# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-27 21:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0193_migratecommentstosalesforce'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='url_slug',
        ),
    ]
