# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-26 15:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_case_record_type_id'),
        ('course_metadata', '0192_draft_version_set_null'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set([('partner', 'key', 'draft'), ('url_slug', 'draft'), ('partner', 'uuid', 'draft')]),
        ),
    ]
