# Generated by Django 1.11.23 on 2019-09-04 18:12


from django.db import migrations


class Migration(migrations.Migration):

    def migrate_data_forward(apps, schema_editor):
        updated_draft_pks = []
        Course = apps.get_model('course_metadata', 'course')
        for instance in Course.everything.all().order_by('draft'):
            # will set the url_slug
            if not instance.draft:
                instance.url_slug = ''
                instance.save()
                # update corresponding draft instance
                if instance.draft_version:
                    instance.draft_version.url_slug = instance.url_slug
                    instance.draft_version.save()
                    updated_draft_pks.append(instance.draft_version.pk)
            elif instance.pk not in updated_draft_pks:
                # update any drafts that do not have published equivalents
                instance.url_slug = ''
                instance.save()

    dependencies = [
        ('core', '0016_add_case_record_type_id'),
        ('course_metadata', '0193_migratecommentstosalesforce'),
    ]

    operations = [
        migrations.RunPython(
            migrate_data_forward,
            migrations.RunPython.noop,
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('partner', 'url_slug', 'draft'), ('partner', 'uuid', 'draft'), ('partner', 'key', 'draft')},
        ),
    ]
