# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-29 18:39
from __future__ import unicode_literals

import course_discovery.apps.course_metadata.managers
from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0194_course_url_slug'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='course',
            managers=[
                ('everything', django.db.models.manager.Manager()),
                ('objects', course_discovery.apps.course_metadata.managers.MigratableCourseDraftManager()),
            ],
        ),
    ]
