# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-27 21:10
from __future__ import unicode_literals

from django.db import migrations
from course_discovery.apps.course_metadata.models import Course

def migrate_data_forward(apps, schema_editor):
    for instance in Course.objects.all():
        instance.save()
        instance.draft_version.url_slug = instance.url_slug
        instance.draft_version.save()
    for instance in Course.everything.filter(draft=True, url_slug=''):
        instance.save()



def migrate_data_backward(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0194_course_url_slug'),
    ]

    operations = [
        migrations.RunPython(
            migrate_data_forward,
            migrate_data_backward,
        ),
    ]
