# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-09 16:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_case_record_type_id'),
        ('course_metadata', '0195_initialize_course_url_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set([('partner', 'uuid', 'draft'), ('partner', 'key', 'draft')]),
        ),
    ]
