# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-27 21:10
from __future__ import unicode_literals

from django.db import migrations

def migrate_data_forward(apps, schema_editor):
    Course = apps.get_model('course_metadata', 'course')
    for instance in Course.objects.all():
        # will set the url_slug
        instance.save()
        instance.draft_version.url_slug = instance.url_slug
        instance.draft_version.save()
    for instance in Course.everything.filter(draft=True, url_slug=''):
        # set url_slugs on any unpublished drafts
        instance.save()

class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0195_alter_course_manager'),
    ]

    operations = [
        migrations.RunPython(
            migrate_data_forward,
            migrations.RunPython.noop,
        ),
    ]
