# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-20 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0196_auto_20190910_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelTypeTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='course_metadata.LevelType')),
            ],
            options={
                'verbose_name': 'LevelType model translations',
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProgramTypeTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
            ],
            options={
                'verbose_name': 'ProgramType model translations',
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.AlterModelOptions(
            name='programtype',
            options={},
        ),
        migrations.AddField(
            model_name='programtypetranslation',
            name='master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='course_metadata.ProgramType'),
        ),
        migrations.AlterUniqueTogether(
            name='programtypetranslation',
            unique_together=set([('language_code', 'master')]),
        ),
        migrations.AlterUniqueTogether(
            name='leveltypetranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
