# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-01 00:43
from __future__ import unicode_literals

from django.core.exceptions import ObjectDoesNotExist
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_case_record_type_id'),
        ('course_metadata', '0198_add_course_type_and_friends'),
    ]

    def migrate_data_forward(apps, schema_editor):
        updated_draft_course_pks = []
        Course = apps.get_model('course_metadata', 'course')
        CourseUrlSlugHistory = apps.get_model('course_metadata', 'courseUrlSlugHistory')
        for instance in Course.everything.all().order_by('draft'):
            current_slug_is_active_on_draft = True
            if instance.draft_version:
                current_slug_is_active_on_draft = instance.url_slug == instance.draft_version.url_slug

            if instance.pk not in updated_draft_course_pks:
                historical_slug = CourseUrlSlugHistory.objects.create(
                    course=instance,
                    partner=instance.partner,
                    is_active=True,
                    is_active_on_draft=current_slug_is_active_on_draft
                )
                # need to set slug after create so it's not overridden with the autoslugification
                historical_slug.url_slug = instance.url_slug
                historical_slug.save()

                if instance.draft_version:
                    if not current_slug_is_active_on_draft:
                        new_draft_slug = CourseUrlSlugHistory.objects.create(
                            course=instance.draft_version,
                            partner=instance.draft_version.partner,
                            is_active=True,
                        )
                        new_draft_slug.url_slug = instance.draft_version.url_slug
                        new_draft_slug.save()
                    updated_draft_course_pks.append(instance.draft_version_id)

    def migrate_data_backwards(apps, schema_editor):
        Course = apps.get_model('course_metadata', 'course')
        CourseUrlSlugHistory = apps.get_model('course_metadata', 'courseUrlSlugHistory')

        def getActiveSlug(course_instance):
            try:
                active_slug = CourseUrlSlugHistory.objects.get(course=course_instance, is_active=True)
                return active_slug.url_slug
            except ObjectDoesNotExist:
                pass

            try:
                official_version = Course.everything.get(draft_version_id=course_instance.id)
                active_slug = CourseUrlSlugHistory.objects.get(course=official_version,is_active_on_draft=True)
                return active_slug.url_slug
            except ObjectDoesNotExist:
                    pass
            return ''

        for instance in Course.everything.all():
            instance.url_slug = getActiveSlug(instance)
            instance.save()


    operations = [
        migrations.CreateModel(
            name='CourseUrlSlugHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('url_slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='course__title')),
                ('is_active', models.BooleanField(default=False)),
                ('is_active_on_draft', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set([('partner', 'uuid', 'draft'), ('partner', 'key', 'draft')]),
        ),
        migrations.AddField(
            model_name='courseurlslughistory',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='url_slug_history', to='course_metadata.Course'),
        ),
        migrations.AddField(
            model_name='courseurlslughistory',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Partner'),
        ),
        migrations.AlterUniqueTogether(
            name='courseurlslughistory',
            unique_together=set([('partner', 'url_slug')]),
        ),
        migrations.RunPython(
            migrate_data_forward,
            migrate_data_backwards
        )
    ]
