# Generated by Django 1.11.25 on 2019-10-04 19:02


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0201_add_organization_slug_remove_marketing_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackpopulateCourseTypeConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arguments', models.TextField(blank=True, default='', help_text='Useful for manually running a Jenkins job. Specify like "--org=key1 --org=key2".')),
            ],
            options={
                'verbose_name': 'backpopulate_course_type argument',
            },
        ),
    ]
