# Generated by Django 1.11.24 on 2019-10-25 19:39


from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0206_seat_type_to_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseurlslug',
            name='url_slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=255, populate_from='course__title'),
        ),
    ]
