# Generated by Django 1.11.24 on 2019-11-08 18:49


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0212_order_course_run_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoveRedirectsConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remove_all', models.BooleanField(default=False, verbose_name='Remove All Redirects')),
                ('url_paths', models.TextField(blank=True, default='', verbose_name='Url Paths')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
