# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-04 20:21
from __future__ import unicode_literals

from django.db import migrations, models


def populate_auto_generate_course_run_keys(apps, schema_editor):
    OrganizationExtension = apps.get_model('publisher', 'OrganizationExtension')
    org_extensions_with_no_auto_create = OrganizationExtension.objects.filter(auto_create_in_studio=False)
    for org_ext in org_extensions_with_no_auto_create:
        org = org_ext.organization
        org.auto_generate_course_run_keys = False
        org.save()


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0213_removeredirectsconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='auto_generate_course_run_keys',
            field=models.BooleanField(default=True, help_text='When this flag is enabled, the key of a new course run will be auto generated.  When this flag is disabled, the key can be manually set.', verbose_name='Automatically generate course run keys'),
        ),
        migrations.RunPython(populate_auto_generate_course_run_keys, migrations.RunPython.noop),
    ]
