# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-12 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0215_add_auto_generate_course_run_keys_to_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetype',
            name='white_listed_orgs',
            field=models.ManyToManyField(blank=True, help_text='Leave this blank to allow all orgs. Otherwise, specifies which orgs can see this course type in Publisher.', to='course_metadata.Organization'),
        ),
    ]
