# Generated by Django 1.11.25 on 2019-11-18 22:01


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0216_add_empty_course_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='leveltype',
            name='sort_value',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
    ]
