# Generated by Django 1.11.25 on 2019-11-01 17:04


from django.db import migrations


def copy_column_values_forwards(apps, schema_editor):
    """
    Copy the order field into the sort_value field.

    This table should have only about 3 rows, so there is no risk of extended
    table locking during this migration.
    """
    LevelType = apps.get_model('course_metadata', 'LevelType')
    for level_type in LevelType.objects.all():
        level_type.sort_value = level_type.order
        level_type.save()


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0217_leveltype_sort_value'),
    ]

    operations = [
        migrations.RunPython(
            copy_column_values_forwards,
            reverse_code=migrations.RunPython.noop,  # Allow reverse migrations, but make it a no-op.
        ),
    ]
