# Generated by Django 1.11.26 on 2019-11-26 17:33


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0221_adds_seat_deadline_overried'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='upgrade_deadline',
            field=models.DateTimeField(blank=True, db_column='upgrade_deadline', null=True),
        ),
        migrations.RenameField(
            model_name='seat',
            old_name='upgrade_deadline',
            new_name='_upgrade_deadline',
        ),
        migrations.AlterField(
            model_name='historicalseat',
            name='upgrade_deadline',
            field=models.DateTimeField(blank=True, db_column='upgrade_deadline', null=True),
        ),
        migrations.RenameField(
            model_name='historicalseat',
            old_name='upgrade_deadline',
            new_name='_upgrade_deadline',
        ),
    ]
