# Generated by Django 1.11.26 on 2019-12-09 14:14


from django.db import migrations, models
import django.db.models.deletion


def null_to_empty(apps, _schema_editor):
    """
    Replaces any None CourseType or CourseRunType values with the special empty type.
    """
    for model_name in ('Course', 'CourseRun'):
        type_model = apps.get_model('course_metadata', model_name + 'Type')
        empty = type_model.objects.get(slug='empty')

        model = apps.get_model('course_metadata', model_name)
        for obj in model.everything.all():
            if obj.type is None:
                obj.type = empty
                obj.save()


def drop_audit_entitlement(apps, _schema_editor):
    """
    Audit course types used to allow audit entitlements to support frontend-app-publisher. That's no longer necessary.
    """
    CourseType = apps.get_model('course_metadata', 'CourseType')
    audit = CourseType.objects.get(slug='audit')
    audit.entitlement_types.clear()

    # Also delete any draft audit entitlements that got created while we were making them.
    CourseEntitlement = apps.get_model('course_metadata', 'CourseEntitlement')
    CourseEntitlement.everything.filter(draft=True, mode__slug='audit').delete()


def set_audit_entitlement(apps, _schema_editor):
    """
    Audit course types used to allow audit entitlements to support frontend-app-publisher. Add it back.
    """
    CourseType = apps.get_model('course_metadata', 'CourseType')
    SeatType = apps.get_model('course_metadata', 'SeatType')
    audit_course_type = CourseType.objects.get(slug='audit')
    audit_seat_type = SeatType.objects.get(slug='audit')
    audit_course_type.entitlement_types.set([audit_seat_type])


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0222_rename_upgrade_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course_metadata.CourseType'),
        ),
        migrations.AlterField(
            model_name='courserun',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course_metadata.CourseRunType'),
        ),
        migrations.RunPython(
            null_to_empty,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            drop_audit_entitlement,
            set_audit_entitlement,
        ),
    ]
