# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-17 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0226_historicalorganization'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorganization',
            name='certificate_name',
            field=models.CharField(blank=True, help_text='If populated, this field will overwrite name in platform.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='certificate_name',
            field=models.CharField(blank=True, help_text='If populated, this field will overwrite name in platform.', max_length=255, null=True),
        ),
    ]
