# Generated by Django 1.11.26 on 2019-12-13 20:36


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0226_historicalorganization'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkModifyProgramHookConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_hooks', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
