# Generated by Django 1.11.26 on 2019-12-18 18:30


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0228_add_certificate_name_to_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courserun',
            name='has_ofac_restrictions',
            field=models.NullBooleanField(choices=[('', '--'), (True, 'Blocked'), (False, 'Unrestricted')], default=None, verbose_name='Add OFAC restriction text to the FAQ section of the Marketing site'),
        ),
        migrations.AlterField(
            model_name='historicalcourserun',
            name='has_ofac_restrictions',
            field=models.NullBooleanField(choices=[('', '--'), (True, 'Blocked'), (False, 'Unrestricted')], default=None, verbose_name='Add OFAC restriction text to the FAQ section of the Marketing site'),
        ),
    ]
