# Generated by Django 1.11.27 on 2020-01-08 19:23


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0230_add_org_image_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalorganization',
            name='banner_image_url',
        ),
        migrations.RemoveField(
            model_name='historicalorganization',
            name='certificate_logo_image_url',
        ),
        migrations.RemoveField(
            model_name='historicalorganization',
            name='logo_image_url',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='banner_image_url',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='certificate_logo_image_url',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='logo_image_url',
        ),
        migrations.AlterField(
            model_name='historicalorganization',
            name='certificate_name',
            field=models.CharField(blank=True, help_text='If populated, this field will overwrite name in platform.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='certificate_name',
            field=models.CharField(blank=True, help_text='If populated, this field will overwrite name in platform.', max_length=255, null=True),
        ),
    ]
