# Generated by Django 1.11.27 on 2020-01-23 16:08


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0232_backfillcourserunslugsconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprogram',
            name='credit_value',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='Number of credits a learner will earn upon successful completion of the program'),
        ),
        migrations.AddField(
            model_name='program',
            name='credit_value',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='Number of credits a learner will earn upon successful completion of the program'),
        ),
    ]
