# Generated by Django 1.11.28 on 2020-02-25 13:40


from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0234_auto_20200207_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courserun',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=255, populate_from=['title', 'key']),
        ),
    ]
