# Generated by Django 1.11.29 on 2020-04-08 19:52


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0237_algoliaproxycourse_algoliaproxyprogram'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlgoliaProxyProduct',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('course_metadata.program',),
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['id'], 'verbose_name_plural': 'People'},
        ),
        migrations.AlterField(
            model_name='courserun',
            name='hidden',
            field=models.BooleanField(default=False, help_text='Whether this run should be hidden from API responses.  Do not edit here - this value will be overwritten by the "Course Visibility In Catalog" field in Studio via Refresh Course Metadata.'),
        ),
        migrations.AlterField(
            model_name='historicalcourserun',
            name='hidden',
            field=models.BooleanField(default=False, help_text='Whether this run should be hidden from API responses.  Do not edit here - this value will be overwritten by the "Course Visibility In Catalog" field in Studio via Refresh Course Metadata.'),
        ),
    ]
