# Generated by Django 2.2.12 on 2020-04-14 15:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0239_auto_20200409_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalcourserun',
            name='history_user',
            field=models.ForeignKey(db_constraint=True, null=True, on_delete=models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
