# Generated by Django 2.2.12 on 2020-04-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0239_auto_20200410_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserun',
            name='end_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='courserun',
            name='start_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcourserun',
            name='end_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcourserun',
            name='start_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
