# Generated by Django 2.2.12 on 2020-04-15 17:36

from django.db import migrations, models
import django.db.models.deletion
import parler.models
import sortedm2m.fields
import taggit_autosuggest.managers


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0240_readd_foreign_key_to_history_user_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programtype',
            options={},
        ),
        migrations.AlterField(
            model_name='course',
            name='draft_version',
            field=models.OneToOneField(blank=True, limit_choices_to={'draft': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_official_version', to='course_metadata.Course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='topics',
            field=taggit_autosuggest.managers.TaggableManager(blank=True, help_text='Pick a tag from the suggestions. To make a new tag, add a comma after the tag name.', related_name='course_topics', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='courseentitlement',
            name='draft_version',
            field=models.OneToOneField(blank=True, limit_choices_to={'draft': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_official_version', to='course_metadata.CourseEntitlement'),
        ),
        migrations.AlterField(
            model_name='courserun',
            name='draft_version',
            field=models.OneToOneField(blank=True, limit_choices_to={'draft': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_official_version', to='course_metadata.CourseRun'),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='draft_version',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'draft': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='course_metadata.Course'),
        ),
        migrations.AlterField(
            model_name='historicalcourseentitlement',
            name='draft_version',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'draft': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='course_metadata.CourseEntitlement'),
        ),
        migrations.AlterField(
            model_name='historicalcourserun',
            name='draft_version',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'draft': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='course_metadata.CourseRun'),
        ),
        migrations.AlterField(
            model_name='historicalseat',
            name='draft_version',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'draft': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='course_metadata.Seat'),
        ),
        migrations.AlterField(
            model_name='program',
            name='courses',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, limit_choices_to={'draft': False}, related_name='programs', to='course_metadata.Course'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='draft_version',
            field=models.OneToOneField(blank=True, limit_choices_to={'draft': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_official_version', to='course_metadata.Seat'),
        ),
        migrations.CreateModel(
            name='ProgramTypeTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='course_metadata.ProgramType')),
            ],
            options={
                'verbose_name': 'ProgramType model translations',
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LevelTypeTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='course_metadata.LevelType')),
            ],
            options={
                'verbose_name': 'LevelType model translations',
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
