# Generated by Django 2.2.12 on 2020-04-23 18:09

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0241_auto_20200415_0643'),
        # historical migrations that use the old ProgramType model, make sure they're run first
        ('edx_catalog_extensions', '0001_squashed_0003_create_publish_to_marketing_site_flag'),
        ('edx_catalog_extensions', '0002_create_professional_certificate_program_type')
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programtype',
            options={},
        ),
        migrations.CreateModel(
            name='ProgramTypeTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name_t', models.CharField(max_length=32, unique=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='course_metadata.ProgramType')),
            ],
            options={
                'db_tablespace': '',
                'unique_together': {('language_code', 'master')},
                'verbose_name': 'program type Translation',
                'db_table': 'course_metadata_programtype_translation',
                'managed': True,
                'default_permissions': (),
            },
        ),
    ]
