# Generated by Django 2.2.12 on 2020-04-27 16:36

from django.db import migrations, models
import django.db.models.deletion
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0241_auto_20200415_0643'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programtype',
            options={},
        ),
        migrations.CreateModel(
            name='ProgramTypeTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name_t', models.CharField(max_length=32)),
                ('master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='course_metadata.ProgramType')),
            ],
            options={
                'unique_together': {('name_t', 'language_code'), ('language_code', 'master')},
                'verbose_name': 'ProgramType model translations',
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
