# Generated by Django 2.2.12 on 2020-04-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0242_auto_20200423_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprogramtype',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='programtype',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
