# Generated by Django 2.2.12 on 2020-04-23 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0244_migrate_program_type_translatable_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programtypetranslation',
            old_name='name_t',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='historicalprogramtype',
            name='name',
        ),
        migrations.RemoveField(
            model_name='programtype',
            name='name',
        ),
    ]
