# Generated by Django 2.2.12 on 2020-04-28 18:01

from django.db import migrations, models
import django.db.models.deletion
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0244_migrate_programtype_name_to_translatable_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelTypeTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name_t', models.CharField(max_length=255)),
                ('master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='course_metadata.LevelType')),
            ],
            options={
                'verbose_name': 'LevelType model translations',
                'unique_together': {('language_code', 'master'), ('language_code', 'name_t')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
