# Generated by Django 2.2.12 on 2020-04-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0245_leveltypetranslation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programtypetranslation',
            name='name_t',
            field=models.CharField(max_length=32, verbose_name='name'),
        ),
    ]
