# Generated by Django 2.2.12 on 2020-04-23 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0245_auto_20200423_1827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programtypetranslation',
            options={'verbose_name': 'ProgramType model translations'},
        ),
        migrations.AlterField(
            model_name='programtypetranslation',
            name='master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='course_metadata.ProgramType'),
        ),
        migrations.AlterModelTable(
            name='programtypetranslation',
            table=None,
        ),
    ]
