# Generated by Django 2.2.12 on 2020-04-23 18:57

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0246_auto_20200423_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelTypeTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name_t', models.CharField(max_length=255, unique=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='course_metadata.LevelType')),
            ],
            options={
                'verbose_name': 'level type Translation',
                'default_permissions': (),
                'db_table': 'course_metadata_leveltype_translation',
                'unique_together': {('language_code', 'master')},
                'managed': True,
                'db_tablespace': '',
            },
        ),
    ]
