# Generated by Django 2.2.12 on 2020-04-28 19:10

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0246_auto_20200428_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programtype',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, help_text='Leave this field blank to have the value generated automatically.', populate_from='name_t', unique=True),
        ),
    ]
