# Generated by Django 2.2.12 on 2020-04-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0247_leveltypetranslation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leveltype',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
