# Generated by Django 2.2.12 on 2020-04-23 18:58

from __future__ import unicode_literals

import logging

from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist
from django.db import migrations

logger = logging.getLogger(__name__)


def forwards_func(apps, schema_editor):
    LevelType = apps.get_model('course_metadata', 'LevelType')
    LevelTypeTranslation = apps.get_model('course_metadata', 'LevelTypeTranslation')

    for levelType in LevelType.objects.all():
        LevelTypeTranslation.objects.create(
            master_id=levelType.pk,
            language_code=settings.PARLER_DEFAULT_LANGUAGE_CODE,
            name_t=levelType.name
        )


def backwards_func(apps, schema_editor):
    LevelType = apps.get_model('course_metadata', 'LevelType')
    LevelTypeTranslation = apps.get_model('course_metadata', 'LevelTypeTranslation')

    for levelType in LevelType.objects.all():
        try:
            translation = LevelTypeTranslation.objects.get(master_id=levelType.pk, language_code=settings.LANGUAGE_CODE)
            levelType.name = translation.name_t
            levelType.save()  # Note this only calls Model.save()
        except ObjectDoesNotExist:
            # nothing to migrate
            logger.exception('Migrating data from LevelTypeTranslation for master_id={} DoesNotExist'.format(levelType.pk))

class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0248_auto_20200423_1917'),
    ]

    operations = [
        migrations.RunPython(forwards_func, backwards_func),
    ]
