# Generated by Django 2.2.12 on 2020-05-18 20:54

from django.db import migrations, models
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0249_copy_level_type_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchDefaultResultsConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_name', models.CharField(max_length=32, unique=True)),
                ('courses', sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='course_metadata.Course')),
                ('programs', sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='course_metadata.Program')),
            ],
        ),
    ]
