# Generated by Django 2.2.12 on 2020-04-23 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0249_migrate_level_type_translatable_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leveltypetranslation',
            old_name='name_t',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='leveltype',
            name='name',
        ),
    ]
