# Generated by Django 2.2.12 on 2020-04-23 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0250_auto_20200423_1923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leveltypetranslation',
            options={'verbose_name': 'LevelType model translations'},
        ),
        migrations.AlterField(
            model_name='leveltypetranslation',
            name='master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='course_metadata.LevelType'),
        ),
        migrations.AlterModelTable(
            name='leveltypetranslation',
            table=None,
        ),
    ]
