# Generated by Django 2.2.16 on 2021-02-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0254_auto_20210201_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='designation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profile_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
