# Generated by Django 2.2.15 on 2020-08-13 14:22

import course_discovery.apps.course_metadata.utils
from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0256_curriculum_membership_uniqueness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='image',
            field=stdimage.models.StdImageField(blank=True, help_text='Add the collaborator image, please make sure its dimensions are 200x100px', null=True, upload_to=course_discovery.apps.course_metadata.utils.UploadToFieldNamePath(path='media/course/collaborator/image/', populate_from='uuid')),
        ),
    ]
