# Generated by Django 2.2.13 on 2020-09-02 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0253_auto_20200825_0827'),
        ('course_metadata', '0257_auto_20200813_1422'),
    ]

    operations = [
    ]
