# Generated by Django 2.2.16 on 2021-04-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0257_add_social_media_type_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='marketing_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
