# Generated by Django 2.2.16 on 2020-10-28 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0258_merge_20200902_0937'),
        ('course_metadata', '0258_auto_20201019_1913'),
    ]

    operations = [
    ]
