# Generated by Django 2.2.16 on 2020-10-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0258_auto_20201019_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmode',
            name='certificate_type',
            field=models.CharField(blank=True, choices=[('honor', 'Honor'), ('credit', 'Credit'), ('verified', 'Verified'), ('professional', 'Professional'), ('executive-education', 'Executive Education')], help_text='Certificate type granted if this mode is eligible for a certificate, or blank if not.', max_length=64),
        ),
        migrations.AlterField(
            model_name='historicalprogram',
            name='card_image_url',
            field=models.URLField(blank=True, help_text='DEPRECATED: Use the card image field', null=True),
        ),
        migrations.AlterField(
            model_name='mode',
            name='certificate_type',
            field=models.CharField(blank=True, choices=[('honor', 'Honor'), ('credit', 'Credit'), ('verified', 'Verified'), ('professional', 'Professional'), ('executive-education', 'Executive Education')], help_text='Certificate type granted if this mode is eligible for a certificate, or blank if not.', max_length=64),
        ),
        migrations.AlterField(
            model_name='program',
            name='card_image_url',
            field=models.URLField(blank=True, help_text='DEPRECATED: Use the card image field', null=True),
        ),
    ]
