# Generated by Django 2.2.16 on 2021-04-29 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0258_subject_marketing_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserun',
            name='is_marketing_price_hidden',
            field=models.BooleanField(default=False, verbose_name='Hide Price'),
        ),
        migrations.AddField(
            model_name='courserun',
            name='is_marketing_price_set',
            field=models.BooleanField(default=False, help_text='Indicates whether the course on marketing site is marked paid', verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='courserun',
            name='marketing_price_value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Price Value'),
        ),
        migrations.AddField(
            model_name='historicalcourserun',
            name='is_marketing_price_hidden',
            field=models.BooleanField(default=False, verbose_name='Hide Price'),
        ),
        migrations.AddField(
            model_name='historicalcourserun',
            name='is_marketing_price_set',
            field=models.BooleanField(default=False, help_text='Indicates whether the course on marketing site is marked paid', verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='historicalcourserun',
            name='marketing_price_value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Price Value'),
        ),
        migrations.AddField(
            model_name='subject',
            name='marketing_id',
            field=models.PositiveIntegerField(blank=True, help_text='This field contains subject post ID from marketing site.', null=True),
        ),
    ]
