# Generated by Django 2.2.16 on 2021-10-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0259_add_price_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserun',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30),
        ),
        migrations.AddField(
            model_name='courserun',
            name='total_raters',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalcourserun',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30),
        ),
        migrations.AddField(
            model_name='historicalcourserun',
            name='total_raters',
            field=models.IntegerField(default=0),
        ),
    ]
