# Generated by Django 2.2.16 on 2020-10-28 18:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0259_depr_program_card_image_url_and_add_exec_ed_cert_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorganization',
            name='key',
            field=models.CharField(db_index=True, help_text="Please do not use any spaces or special characters other than period, underscore or hyphen. This key will be used in the course's course key.", max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalorganization',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='key',
            field=models.CharField(help_text="Please do not use any spaces or special characters other than period, underscore or hyphen. This key will be used in the course's course key.", max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
    ]
