# Generated by Django 2.2.16 on 2022-12-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0260_auto_20211025_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserun',
            name='yt_video_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Youtube Video URL'),
        ),
        migrations.AddField(
            model_name='historicalcourserun',
            name='yt_video_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Youtube Video URL'),
        ),
    ]
