# Generated by Django 2.2.17 on 2020-12-23 16:44

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0260_bulkupdateimagesconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchdefaultresultsconfiguration',
            name='courses',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, limit_choices_to={'draft': 0}, to='course_metadata.Course'),
        ),
        migrations.AlterField(
            model_name='searchdefaultresultsconfiguration',
            name='programs',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, limit_choices_to={'status': 'active'}, to='course_metadata.Program'),
        ),
    ]
