# Generated by Django 2.2.12 on 2020-06-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0262_auto_20230621_1144'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchDefaultResultsConfiguration',
        ),
    ]
