# Generated by Django 2.2.19 on 2021-03-19 11:50

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0261_auto_20201223_1644'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'get_latest_by': 'created', 'ordering': ['created']},
        ),
        migrations.AlterField(
            model_name='course',
            name='collaborators',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, null=True, related_name='courses_collaborated', to='course_metadata.Collaborator'),
        ),
    ]
