# Generated by Django 2.2.19 on 2021-04-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0264_auto_20210329_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorganization',
            name='enable_skills_in_publisher',
            field=models.BooleanField(default=False, help_text='When this flag is enabled, the skill tags will show up in the course edit page in Publisher.', verbose_name='Enable skills in Publisher'),
        ),
        migrations.AddField(
            model_name='organization',
            name='enable_skills_in_publisher',
            field=models.BooleanField(default=False, help_text='When this flag is enabled, the skill tags will show up in the course edit page in Publisher.', verbose_name='Enable skills in Publisher'),
        ),
    ]
