# Generated by Django 2.2.20 on 2021-06-24 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0265_auto_20210416_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalorganization',
            name='enable_skills_in_publisher',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='enable_skills_in_publisher',
        ),
    ]
