# Generated by Django 3.2.11 on 2022-01-28 00:03

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0267_remove_course_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('external_url', models.URLField()),
                ('external_identifier', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='course',
            name='additional_metadata',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_courses', to='course_metadata.additionalmetadata'),
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='additional_metadata',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='course_metadata.additionalmetadata'),
        ),
    ]
