# Generated by Django 3.2.11 on 2022-02-03 09:13

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0268_auto_20220128_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseurlslug',
            name='url_slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, db_collation='utf8_bin', editable=False, max_length=255, populate_from='course__title'),
        ),
    ]
