# Generated by Django 3.2.11 on 2022-02-08 08:51

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0269_alter_courseurlslug_url_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseurlslug',
            name='url_slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=255, populate_from='course__title'),
        ),
    ]
