# Generated by Django 2.2.24 on 2023-10-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200414_0739'),
        ('course_metadata', '0269_depr_program_card_image_url_and_add_exec_ed_cert_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={},
        ),
        migrations.AlterField(
            model_name='historicalprogram',
            name='title',
            field=models.CharField(help_text='The user-facing display title for this Program.', max_length=255),
        ),
        migrations.AlterField(
            model_name='program',
            name='title',
            field=models.CharField(help_text='The user-facing display title for this Program.', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='program',
            unique_together={('partner', 'title')},
        ),
    ]
