# Generated by Django 2.2.16 on 2024-05-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0270_auto_20231024_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserun',
            name='course_certifications',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Course Certifications'),
        ),
        migrations.AddField(
            model_name='courserun',
            name='course_department',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Course Department'),
        ),
        migrations.AddField(
            model_name='courserun',
            name='course_difficulty_level',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Course Difficulty Level'),
        ),
        migrations.AddField(
            model_name='courserun',
            name='course_format',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Course Format'),
        ),
        migrations.AddField(
            model_name='courserun',
            name='course_language',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Course Language'),
        ),
        migrations.AddField(
            model_name='courserun',
            name='course_training_packages',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Course Training Packages'),
        ),
        migrations.AddField(
            model_name='historicalcourserun',
            name='course_certifications',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Course Certifications'),
        ),
        migrations.AddField(
            model_name='historicalcourserun',
            name='course_department',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Course Department'),
        ),
        migrations.AddField(
            model_name='historicalcourserun',
            name='course_difficulty_level',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Course Difficulty Level'),
        ),
        migrations.AddField(
            model_name='historicalcourserun',
            name='course_format',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Course Format'),
        ),
        migrations.AddField(
            model_name='historicalcourserun',
            name='course_language',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Course Language'),
        ),
        migrations.AddField(
            model_name='historicalcourserun',
            name='course_training_packages',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Course Training Packages'),
        ),
    ]
