# Generated by Django 3.2.11 on 2022-03-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0270_alter_courseurlslug_url_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalmetadata',
            name='lead_capture_form_url',
            field=models.URLField(blank=True),
        ),
    ]
