# Generated by Django 3.2.12 on 2022-03-10 16:31

import course_discovery.apps.course_metadata.fields
import course_discovery.apps.course_metadata.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0272_auto_20220307_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('heading', models.CharField(blank=True, max_length=255)),
                ('blurb', course_discovery.apps.course_metadata.fields.NullHtmlField(blank=True, default=None, null=True, validators=[course_discovery.apps.course_metadata.validators.validate_html])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('heading', models.CharField(blank=True, max_length=255)),
                ('blurb', course_discovery.apps.course_metadata.fields.NullHtmlField(blank=True, default=None, null=True, validators=[course_discovery.apps.course_metadata.validators.validate_html])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='additionalmetadata',
            name='certificate_info',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_course_additional_metadata', to='course_metadata.certificateinfo'),
        ),
        migrations.AddField(
            model_name='additionalmetadata',
            name='facts',
            field=models.ManyToManyField(blank=True, related_name='related_course_additional_metadata', to='course_metadata.Fact'),
        ),
    ]
