# Generated by Django 3.2.12 on 2022-03-22 11:14

import course_discovery.apps.course_metadata.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0273_add_facts_and_cert_info_data_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='organization_logo_override',
            field=models.ImageField(blank=True, null=True, upload_to=course_discovery.apps.course_metadata.utils.UploadToFieldNamePath(path='organization/logo_override/', populate_from='uuid'), validators=[django.core.validators.FileExtensionValidator(['png'])]),
        ),
        migrations.AddField(
            model_name='course',
            name='organization_short_code_override',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='organization_logo_override',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(['png'])]),
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='organization_short_code_override',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
