# Generated by Django 3.2.12 on 2022-03-17 18:19

import course_discovery.apps.course_metadata.utils
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0273_add_facts_and_cert_info_data_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='organization_logo_override',
            field=stdimage.models.StdImageField(blank=True, help_text='Please provide an image file with transparent background', null=True, upload_to=course_discovery.apps.course_metadata.utils.UploadToFieldNamePath(path='media/course/org/logo_override/', populate_from='uuid')),
        ),
        migrations.AddField(
            model_name='course',
            name='organization_short_code_override',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='organization_logo_override',
            field=models.TextField(blank=True, help_text='Please provide an image file with transparent background', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='organization_short_code_override',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
