# Generated by Django 3.2.12 on 2022-03-31 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0274_auto_20220322_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalmetadata',
            name='organic_url',
            field=models.URLField(blank=True, help_text='The URL of the paid landing page on external site', max_length=511),
        ),
        migrations.AlterField(
            model_name='additionalmetadata',
            name='external_url',
            field=models.URLField(help_text='The redirect URL of the course on external site', max_length=511),
        ),
        migrations.AlterField(
            model_name='additionalmetadata',
            name='lead_capture_form_url',
            field=models.URLField(blank=True, max_length=511),
        ),
    ]
