# Generated by Django 3.2.12 on 2022-03-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0274_auto_20220322_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalmetadata',
            name='organic_url',
            field=models.URLField(blank=True),
        ),
    ]
