# Generated by Django 3.2.12 on 2022-04-25 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0276_add_bootcamp_modes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalmetadata',
            name='external_url',
            field=models.URLField(help_text='The URL of the paid landing page on external site', max_length=511),
        ),
        migrations.AlterField(
            model_name='additionalmetadata',
            name='organic_url',
            field=models.URLField(blank=True, help_text='The URL of the organic landing page on external site', max_length=511),
        ),
    ]
