# Generated by Django 3.2.13 on 2022-05-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0277_external_urls_help_text_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='value_per_lead',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='value_per_lead',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='historicalprogram',
            name='value_per_lead',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='value_per_lead',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
