# Generated by Django 3.2.12 on 2022-05-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0277_external_urls_help_text_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='search_rank',
            field=models.IntegerField(blank=True, default=0, help_text='Optionally allow weighting of a course in the search by a numerical tier value', null=True),
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='search_rank',
            field=models.IntegerField(blank=True, default=0, help_text='Optionally allow weighting of a course in the search by a numerical tier value', null=True),
        ),
    ]
