# Generated by Django 3.2.12 on 2022-05-24 08:22

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0277_external_urls_help_text_updates'),
    ]

    operations = [
        migrations.CreateModel(
            name='DegreeAdditionalMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('external_url', models.URLField(blank=True, help_text='The redirect URL of the degree on external site', max_length=511)),
                ('external_identifier', models.CharField(blank=True, max_length=255)),
                ('organic_url', models.URLField(blank=True, help_text='The URL of the paid landing page on external site', max_length=511)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='degree',
            name='degree_additional_metadata',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='degree', to='course_metadata.degreeadditionalmetadata'),
        ),
    ]
