# Generated by Django 3.2.13 on 2022-05-27 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0278_auto_20220524_0822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='degree',
            name='degree_additional_metadata',
        ),
        migrations.AddField(
            model_name='degreeadditionalmetadata',
            name='degree',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional_metadata', to='course_metadata.degree'),
        ),
        migrations.AlterField(
            model_name='degreeadditionalmetadata',
            name='organic_url',
            field=models.URLField(blank=True, help_text='The URL of the landing page on external site', max_length=511),
        ),
    ]
