# Generated by Django 3.2.13 on 2022-05-30 14:17

from django.db import migrations, models
import django_extensions.db.fields
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0279_auto_20220527_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('value', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='degree',
            name='specializations',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, null=True, to='course_metadata.Specialization'),
        ),
    ]
