# Generated by Django 3.2.13 on 2022-05-31 12:38

import course_discovery.apps.course_metadata.utils
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ietf_language_tags', '0004_auto_20200804_1401'),
        ('course_metadata', '0280_add_specialization_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprogram',
            name='language_override',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, help_text='Language code specific for this program. Useful field in case there are no courses associated with this program.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ietf_language_tags.languagetag'),
        ),
        migrations.AddField(
            model_name='historicalprogram',
            name='level_type_override',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, help_text='Level type specific for this program. Useful field in case there are no courses associated with this program.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='course_metadata.leveltype'),
        ),
        migrations.AddField(
            model_name='historicalprogram',
            name='organization_logo_override',
            field=models.TextField(blank=True, help_text='A field to override Organization logo specific for this program.', max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(['png'])]),
        ),
        migrations.AddField(
            model_name='historicalprogram',
            name='organization_short_code_override',
            field=models.CharField(blank=True, help_text='A field to override Organization short code alias specific for this program.', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalprogram',
            name='primary_subject_override',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, help_text='Primary subject field specific for this program. Useful field in case there are no courses associated with this program.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='course_metadata.subject'),
        ),
        migrations.AddField(
            model_name='program',
            name='language_override',
            field=models.ForeignKey(blank=True, default=None, help_text='Language code specific for this program. Useful field in case there are no courses associated with this program.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ietf_language_tags.languagetag'),
        ),
        migrations.AddField(
            model_name='program',
            name='level_type_override',
            field=models.ForeignKey(blank=True, default=None, help_text='Level type specific for this program. Useful field in case there are no courses associated with this program.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='course_metadata.leveltype'),
        ),
        migrations.AddField(
            model_name='program',
            name='organization_logo_override',
            field=models.ImageField(blank=True, help_text='A field to override Organization logo specific for this program.', null=True, upload_to=course_discovery.apps.course_metadata.utils.UploadToFieldNamePath(path='organization/logo_override/', populate_from='uuid'), validators=[django.core.validators.FileExtensionValidator(['png'])]),
        ),
        migrations.AddField(
            model_name='program',
            name='organization_short_code_override',
            field=models.CharField(blank=True, help_text='A field to override Organization short code alias specific for this program.', max_length=255),
        ),
        migrations.AddField(
            model_name='program',
            name='primary_subject_override',
            field=models.ForeignKey(blank=True, default=None, help_text='Primary subject field specific for this program. Useful field in case there are no courses associated with this program.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='course_metadata.subject'),
        ),
    ]
