# Generated by Django 3.2.13 on 2022-06-08 17:32

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_user_first_name'),
        ('course_metadata', '0281_program_override_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='course',
            name='product_topics',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='course_metadata.Topic'),
        ),
        migrations.AddField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='parent_topics',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='course_metadata.Topic'),
        ),
        migrations.AddField(
            model_name='topic',
            name='subjects',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, to='course_metadata.Subject'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='banner_image_url',
            field=models.URLField(blank=True, help_text='Deprecated field.', null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='partner',
            field=models.ForeignKey(blank=True, help_text='Deprecated field.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.partner'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, help_text='Deprecated field. Leave this field blank to have the value generated automatically.', populate_from='name'),
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name='TopicTranslation',
        ),
    ]
