# Generated by Django 3.2.12 on 2022-06-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0281_program_override_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprogram',
            name='title',
            field=models.CharField(help_text='The user-facing display title for this Program.', max_length=255),
        ),
        migrations.AlterField(
            model_name='program',
            name='title',
            field=models.CharField(help_text='The user-facing display title for this Program.', max_length=255),
        ),
    ]
