# Generated by Django 3.2.13 on 2022-06-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0283_auto_20220613_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalmetadata',
            name='registration_deadline',
            field=models.DateTimeField(blank=True, default=None, help_text='The suggested deadline for enrollment for marketing purpose', null=True),
        ),
        migrations.AddField(
            model_name='additionalmetadata',
            name='start_date',
            field=models.DateTimeField(blank=True, default=None, help_text='The start date of the external course offering for marketing purpose', null=True),
        ),
    ]
