# Generated by Django 3.2.13 on 2022-07-12 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0288_csv_loader_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='degree',
            name='lead_capture_form_url',
            field=models.URLField(blank=True, help_text='The URL to the form that would be rendered in an iFrame. If a url is supplied, it will override HubSpot form field above.`', null=True),
        ),
    ]
