# Generated by Django 3.2.13 on 2022-07-21 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0289_degree_loader_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='degree',
            name='internal_2u_lead_capture_form_id',
            field=models.URLField(blank=True, help_text='The ID of the internal 2u form that would be rendered in place of the hubspot capture form.`', null=True),
        ),
    ]
