# Generated by Django 3.2.13 on 2022-07-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0289_degree_loader_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='value_per_click_international',
            field=models.IntegerField(blank=True, default=0, help_text='In-year international value per click in U.S. dollars.', null=True, verbose_name='International Value Per Click'),
        ),
        migrations.AddField(
            model_name='course',
            name='value_per_click_usa',
            field=models.IntegerField(blank=True, default=0, help_text='In-year U.S. value per click in U.S. dollars.', null=True, verbose_name='U.S. Value Per Click'),
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='value_per_click_international',
            field=models.IntegerField(blank=True, default=0, help_text='In-year international value per click in U.S. dollars.', null=True, verbose_name='International Value Per Click'),
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='value_per_click_usa',
            field=models.IntegerField(blank=True, default=0, help_text='In-year U.S. value per click in U.S. dollars.', null=True, verbose_name='U.S. Value Per Click'),
        ),
        migrations.AddField(
            model_name='historicalprogram',
            name='value_per_click_international',
            field=models.IntegerField(blank=True, default=0, help_text='In-year international value per click in U.S. dollars.', null=True, verbose_name='International Value Per Click'),
        ),
        migrations.AddField(
            model_name='historicalprogram',
            name='value_per_click_usa',
            field=models.IntegerField(blank=True, default=0, help_text='In-year U.S. value per click in U.S. dollars.', null=True, verbose_name='U.S. Value Per Click'),
        ),
        migrations.AddField(
            model_name='program',
            name='value_per_click_international',
            field=models.IntegerField(blank=True, default=0, help_text='In-year international value per click in U.S. dollars.', null=True, verbose_name='International Value Per Click'),
        ),
        migrations.AddField(
            model_name='program',
            name='value_per_click_usa',
            field=models.IntegerField(blank=True, default=0, help_text='In-year U.S. value per click in U.S. dollars.', null=True, verbose_name='U.S. Value Per Click'),
        ),
    ]
