# Generated by Django 3.2.13 on 2022-07-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0289_degree_loader_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='value_per_click',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='value_per_click',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalprogram',
            name='value_per_click',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='value_per_click',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
