# Generated by Django 3.2.13 on 2022-07-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0290_auto_20220720_1448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='value_per_click',
            new_name='value_per_click_international',
        ),
        migrations.RenameField(
            model_name='historicalcourse',
            old_name='value_per_click',
            new_name='value_per_click_international',
        ),
        migrations.RenameField(
            model_name='historicalprogram',
            old_name='value_per_click',
            new_name='value_per_click_international',
        ),
        migrations.RenameField(
            model_name='program',
            old_name='value_per_click',
            new_name='value_per_click_international',
        ),
        migrations.AddField(
            model_name='course',
            name='value_per_click_us',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='value_per_click_us',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalprogram',
            name='value_per_click_us',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='value_per_click_us',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
