# Generated by Django 3.2.13 on 2022-07-21 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0290_in_year_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='degree',
            name='taxi_form_id',
            field=models.CharField(blank=True, help_text='The ID of the Taxi Form (by 2U) that would be rendered in place of the hubspot capture form.', null=True, max_length=75),
        ),
        migrations.AddField(
            model_name='degree',
            name='taxi_form_grouping',
            field=models.CharField(blank=True, help_text='The grouping of the Taxi Form (by 2U) that would be rendered in place of the hubspot capture form.', null=True, max_length=50),
        ),
    ]