# Generated by Django 3.2.13 on 2022-07-20 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0291_auto_20220720_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='value_per_click_us',
            new_name='value_per_click_usa',
        ),
        migrations.RenameField(
            model_name='historicalcourse',
            old_name='value_per_click_us',
            new_name='value_per_click_usa',
        ),
        migrations.RenameField(
            model_name='historicalprogram',
            old_name='value_per_click_us',
            new_name='value_per_click_usa',
        ),
        migrations.RenameField(
            model_name='program',
            old_name='value_per_click_us',
            new_name='value_per_click_usa',
        ),
    ]
