# Generated by Django 3.2.15 on 2022-08-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0291_degree_taxi_form_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degree',
            name='taxi_form_grouping',
            field=models.CharField(blank=True, default='', help_text='The grouping of the Taxi Form (by 2U) that would be rendered instead of the hubspot capture form', max_length=50),
        ),
        migrations.AlterField(
            model_name='degree',
            name='taxi_form_id',
            field=models.CharField(blank=True, default='', help_text='The ID of the Taxi Form (by 2U) that would be rendered in place of the hubspot capture form', max_length=75),
        ),
    ]
