# Generated by Django 3.2.13 on 2022-07-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0292_auto_20220720_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='value_per_click_international',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='value_per_click_usa',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='value_per_click_international',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='value_per_click_usa',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='historicalprogram',
            name='value_per_click_international',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='historicalprogram',
            name='value_per_click_usa',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='value_per_click_international',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='value_per_click_usa',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
