# Generated by Django 3.2.13 on 2022-08-02 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0292_auto_20220805_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalmetadata',
            name='variant_id',
            field=models.UUIDField(editable=False, help_text='The identifier for a product variant.', null=True),
        ),
    ]
