# Generated by Django 3.2.15 on 2022-08-11 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0290_geotargetingdataloaderconfiguration'),
        ('course_metadata', '0293_additionalmetadata_variant_id'),
    ]

    operations = [
    ]
