# Generated by Django 3.2.15 on 2022-08-12 06:10

from django.db import migrations
import taggit_autosuggest.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('course_metadata', '0293_additionalmetadata_variant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='labels',
            field=taggit_autosuggest.managers.TaggableManager(blank=True, help_text='Pick a tag/label from the suggestions. To make a new tag, add a comma after the tag name.', related_name='program_tags', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
