# Generated by Django 3.2.13 on 2022-08-08 19:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0294_add_tag_manager_to_programs'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MaxValueValidator(90), django.core.validators.MinValueValidator(-90)], verbose_name='Latitude')),
                ('lng', models.DecimalField(decimal_places=6, max_digits=10, validators=[django.core.validators.MaxValueValidator(180), django.core.validators.MinValueValidator(-180)], verbose_name='Longitude')),
            ],
            options={
                'unique_together': {('lat', 'lng')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='geolocation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='course_metadata.geolocation'),
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='geolocation',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='course_metadata.geolocation'),
        ),
        migrations.AddField(
            model_name='historicalprogram',
            name='geolocation',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='course_metadata.geolocation'),
        ),
        migrations.AddField(
            model_name='program',
            name='geolocation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='course_metadata.geolocation'),
        ),
    ]
