# Generated by Django 3.2.15 on 2022-08-23 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0294_add_tag_manager_to_programs'),
        ('course_metadata', '0294_merge_20220811_1832'),
    ]

    operations = [
    ]
