# Generated by Django 3.2.15 on 2022-10-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0297_org_hex_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_length',
            field=models.CharField(blank=True, choices=[('short', 'Short'), ('medium', 'Medium'), ('long', 'Long')], help_text='The actual duration of this course as experienced by learners who complete it.', max_length=64),
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='course_length',
            field=models.CharField(blank=True, choices=[('short', 'Short'), ('medium', 'Medium'), ('long', 'Long')], help_text='The actual duration of this course as experienced by learners who complete it.', max_length=64),
        ),
    ]
