# Generated by Django 3.2.11 on 2022-10-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0298_auto_20221007_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalmetadata',
            name='course_term_override',
            field=models.CharField(max_length=20,verbose_name=('Course override'),help_text=('This field allows for override the default course term'),blank=True),
        ),
    ]
