# Generated by Django 3.2.16 on 2022-10-31 04:36

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import taggit_autosuggest.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('course_metadata', '0299_course_title_override'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(blank=True, default='', help_text='Product title that will appear in meta tag for search engine ranking', max_length=100, null=True)),
                ('description', models.CharField(blank=True, default='', help_text='Product description that will appear in meta tag for search engine ranking', max_length=255, null=True)),
                ('keywords', taggit_autosuggest.managers.TaggableManager(blank=True, help_text='SEO Meta tags for Products', related_name='product_metas', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='additionalmetadata',
            name='product_meta',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_additional_metadata', to='course_metadata.productmeta'),
        ),
    ]
