# Generated by Django 3.2.16 on 2022-11-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0299_course_title_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='degree',
            name='custom_program_duration',
            field=models.CharField(blank=True, help_text='The custom program duration makes it possible to change the duration of the program, in months.', max_length=10, null=True),
        ),
    ]
