# Generated by Django 3.2.16 on 2022-11-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0301_external_product_line_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmeta',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Product title that will appear in meta tag for search engine ranking', max_length=200, null=True),
        ),
    ]
