# Generated by Django 3.2.15 on 2022-11-16 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0302_degree_custom_program_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degree',
            name='custom_program_duration',
            field=models.IntegerField(blank=True, help_text='The custom program duration makes it possible to change the duration of the program, in months.', null=True),
        ),
    ]
