# Generated by Django 3.2.15 on 2022-11-17 17:11

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0302_meta_title_length_increment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxiForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('form_id', models.CharField(blank=True, default='', help_text='The ID of the Taxi Form (by 2U) that would be rendered in place of the hubspot capture form', max_length=75)),
                ('grouping', models.CharField(blank=True, default='', help_text='The grouping of the Taxi Form (by 2U) that would be rendered instead of the hubspot capture form', max_length=50)),
                ('title', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('subtitle', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('post_submit_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='degree',
            name='taxi_form_grouping',
        ),
        migrations.RemoveField(
            model_name='degree',
            name='taxi_form_id',
        ),
        migrations.AddField(
            model_name='historicalprogram',
            name='taxi_form',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='course_metadata.taxiform'),
        ),
        migrations.AddField(
            model_name='program',
            name='taxi_form',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taxi_form', to='course_metadata.taxiform'),
        ),
    ]
