# Generated by Django 3.2.15 on 2022-11-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0303_auto_20221117_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='degree',
            name='program_duration_override',
            field=models.CharField(blank=True, help_text='The custom program duration makes it possible to change the duration of the program, in months.', max_length=20, null=True),
        ),
    ]
