# Generated by Django 3.2.16 on 2023-01-17 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0308_auto_20230111_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalmetadata',
            name='course_term_override',
            field=models.CharField(blank=True, default=None, help_text='This field allows for override the default course term', max_length=20, null=True, verbose_name='Course override'),
        ),
    ]
