# Generated by Django 3.2.16 on 2023-01-04 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0309_alter_additionalmetadata_course_term_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='degree',
            name='display_on_org_page',
            field=models.BooleanField(default=False, help_text="Designates whether the degree should be displayed on the owning organization's page"),
        ),
    ]
