# Generated by Django 3.2.16 on 2023-01-24 21:41

from django.db import migrations, models
import djchoices.choices


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0310_degree_display_on_org_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalmetadata',
            name='external_course_marketing_type',
            field=models.CharField(blank=True, choices=[('short_course', 'Short Course'), ('sprint', 'Sprint'), ('course_stack', 'Course Stack')], default=None, help_text='This field contain external course marketing type specific to product lines', max_length=50, null=True, validators=[djchoices.choices.ChoicesValidator({'course_stack': 'Course Stack', 'short_course': 'Short Course', 'sprint': 'Sprint'})]),
        ),
    ]
