# Generated by Django 3.2.16 on 2023-01-30 12:40

from django.db import migrations, models
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0311_additionalmetadata_external_course_marketing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprogram',
            name='has_ofac_restrictions',
            field=models.NullBooleanField(choices=[('', '--'), (True, 'Blocked'), (False, 'Unrestricted')], default=None, verbose_name='Add OFAC restriction text to the FAQ section of the Marketing site'),
        ),
        migrations.AddField(
            model_name='historicalprogram',
            name='ofac_comment',
            field=models.TextField(blank=True, help_text='Comment related to OFAC restriction'),
        ),
        migrations.AddField(
            model_name='program',
            name='has_ofac_restrictions',
            field=models.NullBooleanField(choices=[('', '--'), (True, 'Blocked'), (False, 'Unrestricted')], default=None, verbose_name='Add OFAC restriction text to the FAQ section of the Marketing site'),
        ),
        migrations.AddField(
            model_name='program',
            name='ofac_comment',
            field=models.TextField(blank=True, help_text='Comment related to OFAC restriction'),
        ),
        migrations.AddField(
            model_name='source',
            name='ofac_restricted_program_types',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text='Programs of these types will be OFAC restricted', related_name='ofac_restricted_source', to='course_metadata.ProgramType'),
        ),
    ]
