# Generated by Django 3.2.16 on 2023-01-31 04:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0312_auto_20230130_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geolocation',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MaxValueValidator(90), django.core.validators.MinValueValidator(-90)], verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='geolocation',
            name='lng',
            field=models.DecimalField(decimal_places=6, max_digits=10, null=True, validators=[django.core.validators.MaxValueValidator(180), django.core.validators.MinValueValidator(-180)], verbose_name='Longitude'),
        ),
    ]
