# Generated by Django 3.2.18 on 2023-02-23 07:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0314_bulkuploadtagsconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geolocation',
            name='lat',
            field=models.DecimalField(decimal_places=11, max_digits=14, null=True, validators=[django.core.validators.MaxValueValidator(90), django.core.validators.MinValueValidator(-90)], verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='geolocation',
            name='lng',
            field=models.DecimalField(decimal_places=11, max_digits=14, null=True, validators=[django.core.validators.MaxValueValidator(180), django.core.validators.MinValueValidator(-180)], verbose_name='Longitude'),
        ),
    ]
