# Generated by Django 3.2.16 on 2023-03-07 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0315_geolocation_updates'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_external_key', models.CharField(help_text='Corresponding organization code in an external product source', max_length=255)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_metadata.organization')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_metadata.source')),
            ],
            options={
                'unique_together': {('source', 'organization_external_key')},
            },
        ),
    ]
