# Generated by Django 3.2.17 on 2023-02-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0315_geolocation_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='excluded_from_search',
            field=models.BooleanField(default=False, help_text='If this box is checked, this item will not be indexed in Algolia and will not show up in search results.', verbose_name='Excluded From Search (Algolia Indexing)'),
        ),
        migrations.AddField(
            model_name='course',
            name='excluded_from_seo',
            field=models.BooleanField(default=False, help_text='If this box is checked, the About Page will have a meta tag with noindex value, so the page will not be indexed by robots.', verbose_name='Excluded From SEO (noindex tag)'),
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='excluded_from_search',
            field=models.BooleanField(default=False, help_text='If this box is checked, this item will not be indexed in Algolia and will not show up in search results.', verbose_name='Excluded From Search (Algolia Indexing)'),
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='excluded_from_seo',
            field=models.BooleanField(default=False, help_text='If this box is checked, the About Page will have a meta tag with noindex value, so the page will not be indexed by robots.', verbose_name='Excluded From SEO (noindex tag)'),
        ),
        migrations.AddField(
            model_name='historicalprogram',
            name='excluded_from_search',
            field=models.BooleanField(default=False, help_text='If this box is checked, this item will not be indexed in Algolia and will not show up in search results.', verbose_name='Excluded From Search (Algolia Indexing)'),
        ),
        migrations.AddField(
            model_name='historicalprogram',
            name='excluded_from_seo',
            field=models.BooleanField(default=False, help_text='If this box is checked, the About Page will have a meta tag with noindex value, so the page will not be indexed by robots.', verbose_name='Excluded From SEO (noindex tag)'),
        ),
        migrations.AddField(
            model_name='program',
            name='excluded_from_search',
            field=models.BooleanField(default=False, help_text='If this box is checked, this item will not be indexed in Algolia and will not show up in search results.', verbose_name='Excluded From Search (Algolia Indexing)'),
        ),
        migrations.AddField(
            model_name='program',
            name='excluded_from_seo',
            field=models.BooleanField(default=False, help_text='If this box is checked, the About Page will have a meta tag with noindex value, so the page will not be indexed by robots.', verbose_name='Excluded From SEO (noindex tag)'),
        ),
    ]
