# Generated by Django 3.2.17 on 2023-03-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0316_organizationmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='excluded_from_search',
            field=models.BooleanField(default=False, help_text='If checked, this item will not be indexed in Algolia and will not show up in search results.', verbose_name='Excluded From Search (Algolia Indexing)'),
        ),
        migrations.AddField(
            model_name='course',
            name='excluded_from_seo',
            field=models.BooleanField(default=False, help_text='If checked, the About Page will have a meta tag with noindex value', verbose_name='Excluded From SEO (noindex tag)'),
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='excluded_from_search',
            field=models.BooleanField(default=False, help_text='If checked, this item will not be indexed in Algolia and will not show up in search results.', verbose_name='Excluded From Search (Algolia Indexing)'),
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='excluded_from_seo',
            field=models.BooleanField(default=False, help_text='If checked, the About Page will have a meta tag with noindex value', verbose_name='Excluded From SEO (noindex tag)'),
        ),
        migrations.AddField(
            model_name='historicalprogram',
            name='excluded_from_search',
            field=models.BooleanField(default=False, help_text='If checked, this item will not be indexed in Algolia and will not show up in search results.', verbose_name='Excluded From Search (Algolia Indexing)'),
        ),
        migrations.AddField(
            model_name='historicalprogram',
            name='excluded_from_seo',
            field=models.BooleanField(default=False, help_text='If checked, the About Page will have a meta tag with noindex value', verbose_name='Excluded From SEO (noindex tag)'),
        ),
        migrations.AddField(
            model_name='program',
            name='excluded_from_search',
            field=models.BooleanField(default=False, help_text='If checked, this item will not be indexed in Algolia and will not show up in search results.', verbose_name='Excluded From Search (Algolia Indexing)'),
        ),
        migrations.AddField(
            model_name='program',
            name='excluded_from_seo',
            field=models.BooleanField(default=False, help_text='If checked, the About Page will have a meta tag with noindex value', verbose_name='Excluded From SEO (noindex tag)'),
        ),
    ]
