# Generated by Django 3.2.18 on 2023-03-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0317_add_fields_to_exclude_from_search_and_seo'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='data_modified_timestamp',
            field=models.DateTimeField(blank=True, default=None, help_text='The last time this course was modified in the database.', null=True),
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='data_modified_timestamp',
            field=models.DateTimeField(blank=True, default=None, help_text='The last time this course was modified in the database.', null=True),
        ),
        migrations.AddField(
            model_name='historicalprogram',
            name='data_modified_timestamp',
            field=models.DateTimeField(blank=True, default=None, help_text='The last time this program was modified.', null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='data_modified_timestamp',
            field=models.DateTimeField(blank=True, default=None, help_text='The last time this program was modified.', null=True),
        ),
    ]
