# Generated by Django 3.2.18 on 2023-04-11 15:04

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0320_allow_blank_exclude_from_search_and_seo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('course_key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('reviews_count', models.IntegerField(help_text='Total number of survey responses associated with a course')),
                ('avg_course_rating', models.DecimalField(decimal_places=6, help_text='Average rating of the course on a 5 star scale', max_digits=7)),
                ('confident_learners_percentage', models.DecimalField(decimal_places=6, help_text='Percentage of learners who are confident this course will help them reach their goals ("Extremely confident" or "Very confident" on survey)', max_digits=9)),
                ('most_common_goal', models.CharField(choices=[('changecareers', 'Change careers'), ('jobadvancement', 'Job advancement'), ('valuableskills', 'Learn valuable skills'), ('learnforfun', 'Learn for fun')], help_text='Most common goal is determined by goal most selected by learners for that course', max_length=255)),
                ('most_common_goal_learners_percentage', models.DecimalField(decimal_places=6, help_text='Percentage of learners who selected the most common goal', max_digits=9)),
                ('total_enrollments', models.IntegerField(help_text='Total no. of enrollments in the course in past 12 months')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
