# Generated by Django 3.2.18 on 2023-04-21 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0321_coursereview'),
        ('course_metadata', '0321_programdataloaderconfiguration'),
    ]

    operations = [
    ]
