# Generated by Django 3.2.18 on 2023-04-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0321_coursereview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvalue',
            name='per_click_international',
            field=models.IntegerField(blank=True, default=5, help_text='International value per click in U.S. dollars.', null=True, verbose_name='International Value Per Click'),
        ),
        migrations.AlterField(
            model_name='productvalue',
            name='per_click_usa',
            field=models.IntegerField(blank=True, default=5, help_text='U.S. value per click in U.S. dollars.', null=True, verbose_name='U.S. Value Per Click'),
        ),
    ]
