# Generated by Django 3.2.18 on 2023-04-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0322_value_per_click_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeduplicateHistoryConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arguments', models.TextField(blank=True, default='', help_text='Useful for manually running a Jenkins job. Specify like "course_metadata.CourseRun -v=3 --dry  --excluded_fields url_slug --m 26280"')),
            ],
            options={
                'verbose_name': 'deduplicate_course_metadata_history argument',
            },
        ),
    ]
