# Generated by Django 3.2.17 on 2023-06-22 09:10

import course_discovery.apps.course_metadata.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course_metadata', '0326_productvaluedataloaderconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseurlslug',
            name='url_slug',
            field=course_discovery.apps.course_metadata.fields.AutoSlugWithSlashesField(blank=True, editable=False, max_length=255, populate_from='course__title'),
        ),
        migrations.CreateModel(
            name='MigrateCourseSlugConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date', models.DateTimeField(auto_now_add=True, verbose_name='Change date')),
                ('enabled', models.BooleanField(default=False, verbose_name='Enabled')),
                ('csv_file', models.FileField(blank=True, help_text='It expects the data will be provided in a csv file format with first row containing all the headers.', null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])])),
                ('course_uuids', models.TextField(blank=True, default=None, null=True, verbose_name='Course UUIDs')),
                ('dry_run', models.BooleanField(default=True)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Changed by')),
            ],
            options={
                'ordering': ('-change_date',),
                'abstract': False,
            },
        ),
    ]
