# Generated by Django 3.2.17 on 2023-06-08 09:26

import course_discovery.apps.course_metadata.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0326_productvaluedataloaderconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseurlslug',
            name='url_slug',
            field=course_discovery.apps.course_metadata.models.AutoSlugWithSlashesField(blank=True, editable=False, max_length=255, populate_from='course__title'),
        ),
    ]
