# Generated by Django 3.2.19 on 2023-07-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0327_create_migrate_course_slug_config_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalmetadata',
            name='display_on_org_page',
            field=models.BooleanField(default=True, help_text="Determines weather the course should be displayed on the owning organization's page"),
        ),
    ]
