# Generated by Django 3.2.20 on 2023-07-17 08:04

from django.db import migrations
import multi_email_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0328_additionalmetadata_display_on_org_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='watchers',
            field=multi_email_field.fields.MultiEmailField(blank=True, default=[], help_text='The list of email addresses that will be notified if any of the course runs is published or scheduled.', verbose_name='Watchers'),
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='watchers',
            field=multi_email_field.fields.MultiEmailField(blank=True, default=[], help_text='The list of email addresses that will be notified if any of the course runs is published or scheduled.', verbose_name='Watchers'),
        ),
    ]
