# Generated by Django 3.2.20 on 2023-07-27 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0329_add_field_watchers'),
    ]

    operations = [
        migrations.AddField(
            model_name='migratecourseslugconfiguration',
            name='course_type',
            field=models.CharField(choices=[('open-course', 'Open Courses'), ('executive-education-2u', '2U Executive Education Courses')], default='open-course', max_length=255),
        ),
        migrations.AddField(
            model_name='migratecourseslugconfiguration',
            name='product_source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course_metadata.source'),
        ),
    ]
