# Generated by Django 3.2.20 on 2023-07-18 14:32

from django.db import migrations, models
import djchoices.choices


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0329_add_field_watchers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalmetadata',
            name='product_status',
            field=models.CharField(choices=[('archived', 'Archived'), ('published', 'Published'), ('active', 'Active'), ('scheduled', 'Scheduled'), ('planned', 'Planned'), ('market_testing', 'Marketing Test'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='published', max_length=50, validators=[djchoices.choices.ChoicesValidator({'active': 'Active', 'archived': 'Archived', 'cancelled': 'Cancelled', 'completed': 'Completed', 'market_testing': 'Marketing Test', 'planned': 'Planned', 'published': 'Published', 'scheduled': 'Scheduled'})]),
        ),
    ]
