# Generated by Django 3.2.20 on 2023-08-10 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0330_add_new_fields_to_migrate_course_slug_config_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalmetadata',
            name='external_course_marketing_type',
            field=models.CharField(blank=True, choices=[('short_course', 'Short Course'), ('sprint', 'Sprint'), ('course_stack', 'Course Stack')], default=None, help_text='This field contain external course marketing type specific to product lines', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='additionalmetadata',
            name='product_status',
            field=models.CharField(choices=[('archived', 'Archived'), ('published', 'Published')], default='published', max_length=50),
        ),
        migrations.AlterField(
            model_name='courserun',
            name='pacing_type',
            field=models.CharField(blank=True, choices=[('instructor_paced', 'Instructor-paced'), ('self_paced', 'Self-paced')], db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='courserun',
            name='status',
            field=models.CharField(choices=[('unpublished', 'Unpublished'), ('review_by_legal', 'Awaiting Review from Legal'), ('review_by_internal', 'Awaiting Internal Review'), ('reviewed', 'Reviewed'), ('published', 'Published')], db_index=True, default='unpublished', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalcourserun',
            name='pacing_type',
            field=models.CharField(blank=True, choices=[('instructor_paced', 'Instructor-paced'), ('self_paced', 'Self-paced')], db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcourserun',
            name='status',
            field=models.CharField(choices=[('unpublished', 'Unpublished'), ('review_by_legal', 'Awaiting Review from Legal'), ('review_by_internal', 'Awaiting Internal Review'), ('reviewed', 'Reviewed'), ('published', 'Published')], db_index=True, default='unpublished', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalprogram',
            name='status',
            field=models.CharField(choices=[('unpublished', 'Unpublished'), ('active', 'Active'), ('retired', 'Retired'), ('deleted', 'Deleted')], db_index=True, default='unpublished', help_text='The lifecycle status of this Program.', max_length=24),
        ),
        migrations.AlterField(
            model_name='program',
            name='status',
            field=models.CharField(choices=[('unpublished', 'Unpublished'), ('active', 'Active'), ('retired', 'Retired'), ('deleted', 'Deleted')], db_index=True, default='unpublished', help_text='The lifecycle status of this Program.', max_length=24),
        ),
    ]
