# Generated by Django 3.2.20 on 2023-09-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0331_auto_20230810_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='migratecourseslugconfiguration',
            name='course_type',
            field=models.CharField(choices=[('open-course', 'Open Courses'), ('executive-education-2u', '2U Executive Education Courses'), ('bootcamp-2u', 'Bootcamps')], default='open-course', max_length=255),
        ),
    ]
