# Generated by Django 4.2.5 on 2023-10-05 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ietf_language_tags', '0004_auto_20200804_1401'),
        ('course_metadata', '0336_update_microbachelors_seat_types'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalcourse',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical course', 'verbose_name_plural': 'historical courses'},
        ),
        migrations.AlterModelOptions(
            name='historicalcourseentitlement',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical course entitlement', 'verbose_name_plural': 'historical course entitlements'},
        ),
        migrations.AlterModelOptions(
            name='historicalcourserun',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical course run', 'verbose_name_plural': 'historical course runs'},
        ),
        migrations.AlterModelOptions(
            name='historicalcourseruntype',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical course run type', 'verbose_name_plural': 'historical course run types'},
        ),
        migrations.AlterModelOptions(
            name='historicalcoursetype',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical course type', 'verbose_name_plural': 'historical course types'},
        ),
        migrations.AlterModelOptions(
            name='historicalcurriculum',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical curriculum', 'verbose_name_plural': 'historical curriculums'},
        ),
        migrations.AlterModelOptions(
            name='historicalcurriculumcoursemembership',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical curriculum course membership', 'verbose_name_plural': 'historical curriculum course memberships'},
        ),
        migrations.AlterModelOptions(
            name='historicalcurriculumcourserunexclusion',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical curriculum course run exclusion', 'verbose_name_plural': 'historical curriculum course run exclusions'},
        ),
        migrations.AlterModelOptions(
            name='historicalcurriculumprogrammembership',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical curriculum program membership', 'verbose_name_plural': 'historical curriculum program memberships'},
        ),
        migrations.AlterModelOptions(
            name='historicaldegreecost',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical degree cost', 'verbose_name_plural': 'historical degree costs'},
        ),
        migrations.AlterModelOptions(
            name='historicaldegreedeadline',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical degree deadline', 'verbose_name_plural': 'historical degree deadlines'},
        ),
        migrations.AlterModelOptions(
            name='historicalmode',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical mode', 'verbose_name_plural': 'historical modes'},
        ),
        migrations.AlterModelOptions(
            name='historicalorganization',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical organization', 'verbose_name_plural': 'historical organizations'},
        ),
        migrations.AlterModelOptions(
            name='historicalprogram',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical program', 'verbose_name_plural': 'historical programs'},
        ),
        migrations.AlterModelOptions(
            name='historicalprogramtype',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical program type', 'verbose_name_plural': 'historical program types'},
        ),
        migrations.AlterModelOptions(
            name='historicalseat',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical seat', 'verbose_name_plural': 'historical seats'},
        ),
        migrations.AlterModelOptions(
            name='historicaltrack',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical track', 'verbose_name_plural': 'historical tracks'},
        ),
        migrations.AlterField(
            model_name='courserun',
            name='video_translation_languages',
            field=models.ManyToManyField(blank=True, related_name='+', to='ietf_language_tags.languagetag'),
        ),
    ]
