# Generated by Django 3.2.22 on 2023-10-10 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0337_alter_historicalcourse_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorganization',
            name='data_modified_timestamp',
            field=models.DateTimeField(blank=True, default=None, help_text='The timestamp of the last time the organization data was modified.', null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='data_modified_timestamp',
            field=models.DateTimeField(blank=True, default=None, help_text='The timestamp of the last time the organization data was modified.', null=True),
        ),
    ]
