# Generated by Django 3.2.22 on 2023-11-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0338_auto_20231010_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserun',
            name='variant_id',
            field=models.UUIDField(blank=True, help_text='The identifier for a product variant. This is used to link a course run to a product variant for external LOBs (i.e; ExecEd & Bootcamps).', null=True),
        ),
        migrations.AddField(
            model_name='historicalcourserun',
            name='variant_id',
            field=models.UUIDField(blank=True, help_text='The identifier for a product variant. This is used to link a course run to a product variant for external LOBs (i.e; ExecEd & Bootcamps).', null=True),
        ),
    ]
