# Generated by Django 3.2.22 on 2023-12-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0339_auto_20231106_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprogram',
            name='marketing_slug',
            field=models.CharField(db_index=True, help_text='Leave this field blank to have the value generated automatically.', max_length=255),
        ),
        migrations.AlterField(
            model_name='program',
            name='marketing_slug',
            field=models.CharField(db_index=True, help_text='Leave this field blank to have the value generated automatically.', max_length=255, unique=True),
        ),
    ]
