# Generated by Django 4.2.13 on 2024-07-05 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0342_additionalmetadata_taxi_form_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='taxi_form',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='program', to='course_metadata.taxiform'),
        ),
    ]
