# Generated by Django 4.2.14 on 2024-07-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0343_alter_program_taxi_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserun',
            name='fixed_price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The fixed USD price for course runs to minimize the impact of currency fluctuations.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalcourserun',
            name='fixed_price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The fixed USD price for course runs to minimize the impact of currency fluctuations.', max_digits=10, null=True),
        ),
    ]
