# Generated by Django 4.2.18 on 2025-02-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0346_archivecoursesconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserun',
            name='ai_languages',
            field=models.JSONField(blank=True, help_text='A JSON dict detailing the available translations and transcriptions for this run. The dict has two keys: translation_languages and transcription_languages.', null=True),
        ),
        migrations.AddField(
            model_name='historicalcourserun',
            name='ai_languages',
            field=models.JSONField(blank=True, help_text='A JSON dict detailing the available translations and transcriptions for this run. The dict has two keys: translation_languages and transcription_languages.', null=True),
        ),
    ]
