# Generated by Django 4.2.18 on 2025-03-04 18:11

import course_discovery.apps.course_metadata.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0347_pathway_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserun',
            name='ai_languages',
            field=models.JSONField(blank=True, help_text='A JSON dict detailing the available translations and transcriptions for this run. The dict has two keys: translation_languages and transcription_languages.', null=True, validators=[course_discovery.apps.course_metadata.utils.validate_ai_languages]),
        ),
        migrations.AddField(
            model_name='historicalcourserun',
            name='ai_languages',
            field=models.JSONField(blank=True, help_text='A JSON dict detailing the available translations and transcriptions for this run. The dict has two keys: translation_languages and transcription_languages.', null=True, validators=[course_discovery.apps.course_metadata.utils.validate_ai_languages]),
        ),
    ]
