# Generated by Django 4.2.18 on 2025-03-07 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0349_alter_courserun_ai_languages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courserun',
            name='translation_languages',
        ),
        migrations.RemoveField(
            model_name='historicalcourserun',
            name='translation_languages',
        ),
    ]
