# Generated by Django 4.2.19 on 2025-04-10 19:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course_metadata', '0350_remove_courserun_translation_languages_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkTasksConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date', models.DateTimeField(auto_now_add=True, verbose_name='Change date')),
                ('enabled', models.BooleanField(default=False, verbose_name='Enabled')),
                ('csv_file', models.FileField(help_text='It expects the data will be provided in a csv file format with first row containing all the headers.', upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])])),
                ('job_summary', models.TextField(blank=True, help_text='Summary of the job', null=True)),
                ('task_type', models.CharField(choices=[('bulk_course_create', 'Bulk Course Create'), ('bulk_course_update', 'Bulk Course Update'), ('bulk_course_partial_update', 'Bulk Course Partial Update'), ('bulk_course_rerun_create', 'Bulk Course Rerun Create'), ('bulk_course_run_update', 'Bulk Course Run Update'), ('bulk_course_run_partial_update', 'Bulk Course Run Partial Update')], help_text='Type of Bulk Task to be performed', max_length=255, verbose_name='Task Type')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Partially Completed', 'Partially Completed'), ('Errored', 'Errored')], default='Pending', max_length=50)),
                ('task_id', models.CharField(blank=True, help_text='Identifier of the celery task associated with this bulk task', max_length=255, null=True, unique=True)),
                ('changed_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Changed by')),
                ('uploader', models.ForeignKey(blank=True, help_text='User who uploaded the file', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bulk_tasks_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-change_date',),
                'abstract': False,
            },
        ),
    ]
