# Generated by Django 4.2.19 on 2025-04-16 08:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course_metadata', '0350_remove_courserun_translation_languages_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkOperationTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('csv_file', models.FileField(help_text='It expects the data will be provided in a csv file format with first row containing all the headers.', upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])])),
                ('task_summary', models.TextField(blank=True, help_text='Summary of the task', null=True)),
                ('task_type', models.CharField(choices=[('course_create', 'Course Create'), ('course_partial_update', 'Course Partial Update'), ('course_rerun', 'Course Rerun'), ('course_run_partial_update', 'Course Run Partial Update')], help_text='Type of Bulk Task to be performed', max_length=255, verbose_name='Task Type')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('partially_completed', 'Partially Completed'), ('errored', 'Errored')], default='pending', help_text='Status of the Bulk Task', max_length=50, verbose_name='Status')),
                ('task_id', models.CharField(blank=True, help_text='Identifier of the celery task associated with this bulk task', max_length=255, null=True, unique=True)),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='User who uploaded the file', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bulk_operation_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
