# Generated by Django 4.2.20 on 2025-04-30 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0351_bulkoperationtask'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curriculum',
            options={},
        ),
        migrations.AlterModelOptions(
            name='degreeadditionalmetadata',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ranking',
            options={},
        ),
    ]
