# Generated by Django 4.2.20 on 2025-04-30 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0352_alter_curriculum_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkoperationtask',
            name='task_summary',
            field=models.JSONField(blank=True, help_text='Summary of the task', null=True),
        ),
    ]
