# Generated by Django 4.2.20 on 2025-05-15 12:33

import course_discovery.apps.course_metadata.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0353_alter_bulkoperationtask_task_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkoperationtask',
            name='csv_file',
            field=models.FileField(help_text='It expects the data will be provided in a csv file format with first row containing all the headers.', upload_to=course_discovery.apps.course_metadata.utils.UploadToFieldNamePath(path='bulk_operations/', populate_from='created'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])]),
        ),
    ]
