# Generated by Django 4.2.20 on 2025-06-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0354_bulk_operation_upload_to_addition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkoperationtask',
            name='task_type',
            field=models.CharField(choices=[('course_create', 'Course Create'), ('partial_updates', 'Partial Update'), ('course_rerun', 'Course Rerun')], help_text='Type of Bulk Task to be performed', max_length=255, verbose_name='Task Type'),
        ),
    ]
