# Generated by Django 4.2.20 on 2025-06-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0355_alter_bulkoperationtask_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkoperationtask',
            name='task_type',
            field=models.CharField(choices=[('course_create', 'Course Create'), ('partial_updates', 'Partial Update'), ('course_rerun', 'Course Rerun'), ('course_editor_update', 'Course Editor Update')], help_text='Type of Bulk Task to be performed', max_length=255, verbose_name='Task Type'),
        ),
    ]
