# Generated by Django 4.2.23 on 2025-10-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0356_add_course_editor_update_bulk_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalseat',
            name='credit_hours',
            field=models.IntegerField(blank=True, help_text='Number of credit hours awarded for this seat.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalseat',
            name='credit_provider',
            field=models.CharField(blank=True, help_text='The provider granting academic credit for this seat, if applicable.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seat',
            name='credit_hours',
            field=models.IntegerField(blank=True, help_text='Number of credit hours awarded for this seat.', null=True),
        ),
        migrations.AlterField(
            model_name='seat',
            name='credit_provider',
            field=models.CharField(blank=True, help_text='The provider granting academic credit for this seat, if applicable.', max_length=255, null=True),
        ),
    ]
