# Generated by Django 5.2.12 on 2026-07-10 13:33

from django.db import migrations, models


def update_row_format(apps, schema_editor):
    if schema_editor.connection.vendor != "mysql":
        return

    tables = [
        "course_metadata_course",
        "course_metadata_historicalcourse",
    ]

    with schema_editor.connection.cursor() as cursor:
        for table in tables:
            cursor.execute(
                """
                SELECT ROW_FORMAT
                FROM information_schema.tables
                WHERE table_schema = DATABASE()
                  AND table_name = %s
                """,
                [table],
            )

            result = cursor.fetchone()

            if result and result[0] and result[0].upper() != "DYNAMIC":
                cursor.execute(
                    f"ALTER TABLE {schema_editor.quote_name(table)} ROW_FORMAT=DYNAMIC"
                )


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0358_remove_b2c_subscription_after_revert'),
    ]

    operations = [
        migrations.RunPython(
            update_row_format,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name='course',
            name='b2c_subscription_inclusion',
            field=models.BooleanField(blank=True, default=False, help_text='This field signifie if this course is in the B2C subscription catalog'),
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='b2c_subscription_inclusion',
            field=models.BooleanField(blank=True, default=False, help_text='This field signifie if this course is in the B2C subscription catalog'),
        ),
    ]
