# Generated by Django 5.2.12 on 2026-08-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0361_bulkoperationtask_cm_bo_task_created_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='b2c_subscription_inclusion',
            field=models.BooleanField(blank=True, default=False, help_text='Signifies whether this course is included in the B2c subscription catalog.'),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='b2c_subscription_inclusion',
            field=models.BooleanField(blank=True, default=False, help_text='Signifies whether this course is included in the B2c subscription catalog.'),
        ),
        migrations.AlterField(
            model_name='historicalprogram',
            name='b2c_subscription_inclusion',
            field=models.BooleanField(blank=True, default=False, help_text='Signifies whether this program is included in the B2c subscription catalog.'),
        ),
        migrations.AlterField(
            model_name='program',
            name='b2c_subscription_inclusion',
            field=models.BooleanField(blank=True, default=False, help_text='Signifies whether this program is included in the B2c subscription catalog.'),
        ),
    ]
