# Generated by Django 4.2.14 on 2024-12-24 09:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_metadata', '0345_courserun_translation_languages_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerticalFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=255, populate_from='name', unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Vertical Filters',
                'ordering': ['name'],
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='SubVericalFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=255, populate_from='name', unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('vertical_filters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_vertical_filters', to='tagging.verticalfilter')),
            ],
            options={
                'verbose_name_plural': 'Sub Vertical Filters',
                'ordering': ['name'],
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='ProgramVericalFilters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_verticals', to='course_metadata.program')),
                ('sub_vertical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_sub_vertical_filters', to='tagging.subvericalfilter')),
                ('vertical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_vertical_filters', to='tagging.verticalfilter')),
            ],
            options={
                'verbose_name_plural': 'Program Verticals',
                'ordering': ['program__title'],
                'unique_together': {('program', 'vertical')},
            },
        ),
        migrations.CreateModel(
            name='CourseVerticalFilters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vertical_filters', to='course_metadata.course')),
                ('sub_vertical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_sub_vertical_filters', to='tagging.subvericalfilter')),
                ('vertical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_vertical_filters', to='tagging.verticalfilter')),
            ],
            options={
                'verbose_name_plural': 'Course Vertical Filters',
                'ordering': ['course__title'],
                'unique_together': {('course',)},
            },
        ),
    ]
