# Generated by Django 4.2.14 on 2024-12-24 11:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tagging', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerticalFilterTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('content_type', models.CharField(choices=[('course', 'Course'), ('program', 'Program'), ('degree', 'Degree')], max_length=10)),
                ('object_id', models.UUIDField()),
                ('sub_vertical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_vertical_filters', to='tagging.subvericalfilter')),
                ('vertical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vertical_filters', to='tagging.verticalfilter')),
            ],
            options={
                'ordering': ['content_type', 'object_id'],
                'unique_together': {('content_type', 'object_id', 'vertical')},
            },
        ),
    ]
