# Generated by Django 4.2.11 on 2025-01-28 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tagging', '0002_updatecourseverticalsconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursevertical',
            name='course',
            field=models.OneToOneField(limit_choices_to={'draft': False}, on_delete=django.db.models.deletion.CASCADE, related_name='product_vertical', to='course_metadata.course'),
        ),
    ]
